### ISSUE TITLE
[Bug]Items duplicating in the combat bar (not dropping upon death)

### ISSUE THREAD

**Issue by Kajjou** [promcteam/proskillapi#1]
**Describe the bug**
This is a bug that can make it possible to duplicated items using SkillApi and the Combat bar mode. **DUE TO /CLASS RELOAD** (SKillapi is saving the items in the bar in the wrong way from my intuition)
```
   Whether or not to use the combat bar implementation. Details:
  - Specified slot becomes a toggle item
  - Can optionally move over or require interacting (left, right, or drop) to swap modes
  - Swaps between combat mode and passive mode
  - In combat mode, works like the classic skill bar
  - In passive mode, no skills are shown
  - Passive and combat modes each have their own stored contents
  - combat mode uses the skill bar settings
  combat: 'true'
```
Using this config ^

**To Reproduce**
1. Put items in your combat bar along your others skills (these are cast items) and /class Reload with the bar **closed**
2. Die with the bar **open** (so your skills are visible and your item in the slots 1-9)
3. Just respawn and you will keep the items that were stored in the bar, and on your death location it's just going to drop your items (so you get them twice)

These are all the cases where the duplication happens 
- If you reload with the bar closed, having an item in the combat bar and then dies with the bar open
- If you reload with the bar open, having an item in the combat bar and then dies with the bar open

Duplication doesn't happen in these cases 
- If you reload with the bar closed, having an item in the combat bar and then dies with the bar closed
- If you reload with the bar open, having an item in the combat bar and then dies with the bar closed

**Expected behavior**
It is supposed to drop all the items in your inventory whenever you die (so combat bar items / normal inventory-hotbar items)

**Versions**
 - Server Version: 1.12 - Using Mohist
 - Plugin Version: 1.98

**Comment by goflishMC** [comment]
This is issue is fixed in Dev Build 1.1.3
