### ISSUE TITLE
[Enhancement] Added commands to decrease level and experience

### ISSUE THREAD

**Issue by EyatMC** [promcteam/proskillapi#103]
**I need a command to decrease your level and experience!**

>ex)  reduces Eyat's level by 3.
> /class level Eyat -3 Class

>ex)  Reduces Eyat's experience by 200.
> /class exp Eyat -200 Class

Through this command, you can have a more complete system by linking with other plugins.

**Comment by goflishMC** [comment]
Add 2 new commands:
<pre>
/class forceexp <player> <up/down/reset>
/class forcelevel <player> <up/down/reset>
</pre>
