### ISSUE TITLE
[Bug]: Change World

### ISSUE THREAD

**Issue by KingTatouille** [promcteam/proskillapi#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I change World I got this error in console.

### Steps To Reproduce

Change world and got this.

### Environment

```markdown
- Server Software: Paper 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version:1.0.3.1
- Plugins: https://imgur.com/MUfpbnv
```

### latest.log

https://pastebin.com/SAgv8xZ4

**Comment by Travja** [comment]
Potentially related to #100

**Comment by Travja** [comment]
Paste is expired. Error potentially resolved by recent updates. Will close until further information.
