### ISSUE TITLE
[Bug]: Synchronization is not working properly.

### ISSUE THREAD

**Issue by EyatMC** [promcteam/proskillapi#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
/class changeclass \<player> \<group> \<class>
I changed the class of the player using this command.
However, the scoreboard and skill bar have not been changed.

To fix this (temporary), you need to reconnect.

For better understanding, I made a script to be displayed in the chat.
**VIDEO**
[https://www.dropbox.com/s/5okoxh76ogcfq8n/%EB%85%B9%ED%99%94_2021_10_18_00_03_32_812.mp4?dl=0](https://www.dropbox.com/s/5okoxh76ogcfq8n/%EB%85%B9%ED%99%94_2021_10_18_00_03_32_812.mp4?dl=0)

### Expected Behavior

/class changeclass \<player> \<group> \<class>
With this command, everything should take effect immediately.

### Environment

```markdown
- Server Software: Paper
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://imgur.com/Kk0eZ9I
```

**Comment by goflishMC** [comment]
From my testing and conversation with @Travja  https://i.imgur.com/DM4bWmZ.jpeg
