### ISSUE TITLE
[Enhancement]  Add more placeholders

### ISSUE THREAD

**Issue by Command1264** [promcteam/proskillapi#11]
**Is your feature request related to a problem? Please describe.**
Hope can add more placeholders, otherwise it will be difficult to use.
(My English is not good, forgive me)

**Additional context**
(like this)
https://www.spigotmc.org/resources/skillapi-placeholder-plus.45628/

**Comment by goflishMC** [comment]
We plan to add more placeholders, it's on our list.

**Comment by Command1264** [comment]
should not

**Comment by goflishMC** [comment]
placeholders added in dev build Alpha 1.1
