### ISSUE TITLE
[Bug]:  Custom formula doesn't seem to work

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried editing the custom formula for leveling up, but it didn't seem to work. When I edited the standard values, the x y and z, I did notice that it took longer/shorter to level up based on the numbers I used.

You can find these settings in the main config.yml

reference to our conversation: https://i.imgur.com/eyhyS8f.jpeg

### Expected Behavior

When setting the custom formula to true, it should use that formula to determine how much exp you need to level up.

### Environment

```markdown
- Server Software: Paper 1.17.1
- ProSkillAPI Version: 1.1.7.0.3
- ProMCCore Version: 1.0.3.1
- Plugins: https://i.imgur.com/i55YU2N.jpeg
```

**Comment by Travja** [comment]
Doesn't appear to be broken, actually.

**Comment by goflishMC** [comment]
We can close this. Nobody else reported any issues with it.
