### ISSUE TITLE
[Bug]: Taunt not work with MythicMobs

### ISSUE THREAD

**Issue by SskyWorms** [promcteam/proskillapi#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/54969382/138537472-c15571e4-faea-4072-a9b9-4266168230ca.png)
Here is my current skill, i also enable ThreatTable in every Mythicmobs's mobs but not working, please check

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
I'm a little confused at how this should work. When a MythicMobs mob gets damaged, it will target the player anyway, so why are you trying to taunt the entity when it gets damaged? It should be targeting the player either way.

**Comment by goflishMC** [comment]
You didn't set the skill up correctly. I tested taunt and vanilla mobs and mythicmobs, it works perfect. Here's an example skill you can test. https://pastebin.com/mNkQQ5Tv
