### ISSUE TITLE
[Bug]:  Duped skill icons

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you shift + right click into the non-allocated slots in the hotbar for the skill icons they will get duplicted.

See this for better understanding: https://i.imgur.com/3xRgh5J.jpeg

I tested and confirmed this is a bug.

### Expected Behavior

skill icons should not get duped.

### Steps To Reproduce

See the image to reproduce.

### Environment

```markdown
- Server Software: paper 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://i.imgur.com/JMe3ROK.jpeg
```

**Comment by Travja** [comment]
This isn't actually a bug. It allows the user to adjust and modify their skill bar on their own. Right clicking on slots in the hotbar adds/removes new casting slots [see here.](https://github.com/promcteam/proskillapi/blob/163fdda6cf6941ebdf8a70f7a0393f53ff00ea69/src/main/java/com/sucy/skill/listener/BarListener.java#L273) The slots can then be assigned to by doing `/class skill` and hitting the corresponding number on a skill to assign it to that slot.
