### ISSUE TITLE
[Bug]: When professing to a sub class, attributes get reset

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure if this is intentional, but when you profess into a subclass any attributes you invested in get reset back to zero. This means any stats that were increased before upgrading your class gets put back to 0.

### Steps To Reproduce

Setup a subclass (contact me for this setup and I'll send my files)

When you reach the max level of your class you'll be able to do /class profess and then join the sub class.

When you join the sub class, any attributes you invested will get reset.

### Environment

```markdown
- Server Software: paper 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://i.imgur.com/JMe3ROK.jpeg
```

**Comment by lordsrubka5** [comment]
Sub classes currently just reset all your class progress and give you a brand new class.
Would be nice if there could be a config option for if we want to reset level (and attributes), that way when professing to a new class only thing that would change is base stats of the class, stat scaling and skill tree (refund all skill points on profess too)

**Comment by Svastojed** [comment]
This issue got opened cause of me originally, did you guys manage to fix it so you retain the skills and stats/attributes?
