### ISSUE TITLE
[Bug]:  Pre-configured attributes from the editor don't show in game

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you add starting attributes in the editor under classes, the points you add don't show up in game. However, it still gives you the stat increases as if you had the points, you just don't see them.

These are the attributes I'm talking about that are on the editor for classes that allow you to give that class some starting points. https://i.imgur.com/1zvBsse.jpeg

When you add your class files to your server, the attributes gui does not show your starting points, https://i.imgur.com/PzYLAFu.jpeg. It displays it as 0 points.

### Expected Behavior

If I put 30 in strength attribute on the editor when I add my class files in game and join that class I should have 30 points already in strength attribute.

### Steps To Reproduce

Add points to attributes on the editor in your class.

Upload the class file to your server.

Join the class.

Check your attributes with /class attr and you'll see that it's at 0 instead of however many points you allocated on the editor.

### Environment

```markdown
- Server Software: paper 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://i.imgur.com/JMe3ROK.jpeg
```

**Comment by lordsrubka5** [comment]
This is not really a bug. In /class attr the default number in the brackets is how many points you have invested into that attribute aka how many points you manually added with the points gained from leveling up.  You have to put {total} to include the attributes gained from other sources like default ones from levels, items (and skills? didnt test)
![image](https://user-images.githubusercontent.com/74104790/146419490-24a7b2e5-a386-4c8f-9e87-d1331b6470ae.png)
![image](https://user-images.githubusercontent.com/74104790/146419602-c0d7ac25-24de-433b-957e-821ce65a9316.png)
