### ISSUE TITLE
[Bug] Use skillapi's skill to damage Sentinel

### ISSUE THREAD

**Issue by EyatMC** [promcteam/proskillapi#117]
the skill of skillapi does not damage Sentinel's NPC. please make this possible

https://www.dropbox.com/s/h5sqeaq8o9j3thm/%EB%85%B9%ED%99%94_2021_10_27_00_35_21_407.mp4?dl=0hey

**↓** This is the sentinel plugin github.
https://github.com/mcmonkeyprojects/Sentinel/blob/master/README.md

**Comment by goflishMC** [comment]
do you still have this issue?

**Comment by EyatMC** [comment]
> do you still have this issue?

Yes I still have this problem.

**Comment by Travja** [comment]
Possibly related to #184, though it appears that JennaDiamonds has been able to get the Sentinel to take damage without issues.

**Comment by EyatMC** [comment]
Strange.. I tested by uninstalling all plugins except sentinel and proskillapi only.
But still couldn't deal damage to sentinel with proskillapi's skill (however, attacking with vanilla weapon takes damage).

**Comment by bladesmantis** [comment]
**Update: 09/29/2023**

Ability Info (Screenshot Attached):
- After channeling, stun the 3 closest enemies and deal 10% of their Max HP as damage.

Issue:
- Hostile NPC's spawned via Sentinels plugin cannot be targeted by ProSkillAPI, see attached video.

Discord Forum Link: https://discord.com/channels/818973833570680882/1156466291599757452

https://github.com/promcteam/proskillapi/assets/146367488/a88f4d3d-c2f4-4385-9a92-c3ccd0cdde38

![image](https://github.com/promcteam/proskillapi/assets/146367488/2bbd3208-c51c-4908-ac50-55ab7bc5bffa)

**Comment by Travja** [comment]
I don't know why it took me this long to find. Looks like there's an option in the main config. `Targeting.affect-npcs` should be set to true to allow damaging sentinel mobs.
