### ISSUE TITLE
[Enhancement] add use custommodeldata

### ISSUE THREAD

**Issue by Command1264** [promcteam/proskillapi#12]
**Is your feature request related to a problem? Please describe.**
When I want use cmd(custommodeldata), I can't use cmd on the Unassigned skill item
I guess skill have same problem

**Additional context**
![ewewew](https://user-images.githubusercontent.com/50344708/118356660-ecfbf300-b5a8-11eb-938d-0ff9c53a765f.png)
![螢幕擷取畫面 2021-05-15 180618](https://user-images.githubusercontent.com/50344708/118356662-eff6e380-b5a8-11eb-8372-ae44f6a14607.png)

**Comment by goflishMC** [comment]
Have you tried enabling these options in the config.yml?

![image](https://i.imgur.com/IJ1D26S.png)

![image](https://i.imgur.com/4XPFwgO.png)

**Comment by Command1264** [comment]
Sorry, I did not see it.
