### ISSUE TITLE
add skill cooldown placeholderapi

### ISSUE THREAD

**Issue by willie666687** [promcteam/proskillapi#122]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add add skill cooldown placeholderapi 
like %sapi_default_skillcooldown% if the player has any skill is cooling down

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by Travja** [comment]
We do have `%sapi_dynamic_cooldown_<skill>%`. This should be adequate for most scenarios.
