### ISSUE TITLE
[Bug]: Particles and Block mechanics do not change direction based on player

### ISSUE THREAD

**Issue by RattusApparatus** [promcteam/proskillapi#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using particles or the block mechanic, when facing certain directions the skill will not place down the same. Such as when creating a wall with the mentioned mechanics, they will be to the side of the player or vertical when facing some directions, but then horizontal the other directions.

### Expected Behavior

The blocks and particles should be changing with my direction, making them horizontal to the player and allowing a wall of the object within the skill parameters.

### Steps To Reproduce

1. Use the block or particle animation mechanic
2. Set the block or wall to be in a wall shape, such as by making the block mechanic be 1 block thin, but 5 blocks wide on another axis.
3. When using the skill facing any direction will change where the skill places based on the player.

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by goflishMC** [comment]
please complete the following:

- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:

**Comment by Travja** [comment]
I've addressed the Block Mechanic rotation, but I'm not sure what you might want adjusted in terms of the particle mechanic. I understand that the circles/spheres that it has use a dx/dz that could be adjusted based on the player's rotation, but is that important enough to make a change for?
