### ISSUE TITLE
[Bug]: Skillapi modifies base attack speed

### ISSUE THREAD

**Issue by RebelRanger** [promcteam/proskillapi#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Noticed a very strange issue when using skillapi in relation to attack speed. It seems that after professing into a blank class the attack speed cooldown is reduced. For example a sword normally has an attack speed of 1.5. After professing into the class it's 5+. Unprofessing from the class doesn't fix this. Currently the only way I've found to fix this is to delete playerdata in the world file and the players file in ProSkillAPI, however the issue will occur as soon as you profess into the class again. 

### Steps To Reproduce

1. Create a test server with only ProMcCore and ProSkillAPI. 
2. Create a blank class with no abilities/attributes.
3. Launch the server and observe normal attack speed.
4. Profess into class.
5. The attack speed will be greatly increased. 

### Environment

```markdown
- Server Software: paper-1.17.1-353
- ProSkillAPI Version: ProSkillAPI-1.1.7.4-ALPHA
- ProMCCore Version: ProMCCore-1.0.3.1-ALPHA
- Plugins: ProMCCore, ProSkillAPI
```

**Comment by lordsrubka5** [comment]
Happens to me too, had to give all classes 1 attribute into attack speed that divides the base value by 1000 to fix it
![atkspd](https://user-images.githubusercontent.com/74104790/146418692-9f606554-7c3d-48c0-a382-2ded518e1fb9.png)
