### ISSUE TITLE
[Enhancement] New Trigger: Unequip Armor

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#129]
This trigger would happen when the player unequips an armor piece. (if possible, detect which armor piece)

Options:

Mana: true/false: does this trigger check for mana cost
Cooldown: true/false Does this trigger check if is on cooldown
ArmorType: Chestplate,Helmet,Leggings,Boots (drop down list)

**Comment by Travja** [comment]
Since the existing ArmorEquipTrigger fires when you both put on an armor piece as well as take it off, I'm going to go ahead and close this.
