### ISSUE TITLE
[Bug] Blood deduction is not true.

### ISSUE THREAD

**Issue by Command1264** [promcteam/proskillapi#13]
**Describe the bug**
Blood deduction is not true.

**To Reproduce**
Example steps (replace with your steps)
1. config.GUI.old-health-bar: 'true'
2. reload plugin
3. when your health > 20 (Maybe. I only test ender pearl and potion)

**Expected behavior**
Only deduct 5 blood(ender pearl)

**latest.log**
1. Stop your server
2. Start your server
3. Stop your server
4. Copy your latest.log to https://pastebin.com/
5. https://pastebin.com/7Bz5be2F

**Versions (please complete the following information):**
-  Spigot Version : CraftBukkit version 3069-Spigot-bd6b566-51e2981 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Server Version : 1.16.5
 - Plugin Version : 1.98

**Additional info**
https://youtu.be/-YHjL2hCF9w

**Comment by goflishMC** [comment]
Can you give us your skill file?

**Comment by Command1264** [comment]
[SkillAPI.zip](https://github.com/promcteam/proskillapi/files/6512089/SkillAPI.zip)
