### ISSUE TITLE
[Enhancement] New Trigger: onTimer

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#135]
Description in editor: This will cast a skill every X seconds.

Options:

<pre>
#Tooltip: Does this trigger require mana cost? If using with mobs mana is ignored.
Mana: true/false
#Tooltip: This is the skill that will cast in the interval set in timer.
Skill: skill
#Tooltip: How often the skill will be triggered in seconds, for 1 tick use .05
Timer: timeInSeconds
</pre>

**Comment by Sentropic** [comment]
Yeah this is the Passive Trigger.
