### ISSUE TITLE
[Enhancement] New Condition: Damage Amount

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#148]
This condition would check to see if the player is on fire before executing.

Options:

Icon Key: <key>
Mana: true/false: does this trigger check for mana cost
Cooldown: true/false Does this trigger check if is on cooldown
Type: flat/percent
MinValue: <amount> + <perLevelAmount>
MaxValue: <amount> + <perLevelAmount>

**Comment by Travja** [comment]
There's a little bit of conflicting info on this ticket, but I think all bases are covered anyway. We have the Fire condition and a value condition. The value condition can be used with the `api-damage` value from the Physical/Skill Damage Taken triggers to run mechanics after that.
