### ISSUE TITLE
[Bug]: Particle Effect 

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If multiple skills have particle effect mechanics, only the one that is used first after loading the plugin will be applied to every skill

### Expected Behavior

Each skill using the effect that is set in its own file

### Steps To Reproduce

Make 2 skills that both have particle effect mechanic that are clearly different
Use them on the server
What skill is casted first after loading (or reloading) the plugin will apply its particle effect to other skills used after

### Environment

```markdown
- Server Software: Paper 1.17.1-328
- ProSkillAPI Version: 1.1.7.4-ALPHA
- ProMCCore Version: 1.0.3.2-ALPHA
- Plugins:
AntiDrop, AuthMe, BungeeGuard, Chunky, ChunkyBorder, Citizens, CMI, CMILib, CoreProtect, CrateReloaded, CreativeManager, dtlTraders, dtlTradersPlus, EasyWhitelist*, EnchLimiter, FastAsyncWorldEdit (WorldEdit), LibsDisguises, LuckPerms, MCCore*, MiniaturePets, MobFarmManager, ModelEngine, Multiverse-Core, MythicMobs, PlaceholderAPI, ProMCCore, ProRPGItems, ProSkillAPI, ProtocolLib, ProtocolSupport, Scoreboard-revision*, TAB, TimeIsMoney, TradeMe, Vault, VotingPlugin, Vulcan
```

**Comment by goflishMC** [comment]
Did you give each one a unique "Effect Key"

see this image: https://i.imgur.com/L7chBvm.jpeg

**Comment by lordsrubka5** [comment]
Most likely not, I dont have the issue anymore since i pay attention to that so I guess it can be closed
