### ISSUE TITLE
[Bug]: ProSkillApi Error [RoyaleEconomy]

### ISSUE THREAD

**Issue by JasperRuiz97** [promcteam/proskillapi#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ProSkillApi does not work and does not run when RoyaleEconomy is installed.

or RoyaleEconomy not working with ProSkillApi installed...

The server is shutting down.

### Expected Behavior

I want the plugins to be compatible with each other.

### Environment

```markdown
- Server Software: 1.16.5 Paper
- ProSkillAPI Version: 1.1.7.8
- ProMCCore Version: 1.0.3.2
- Plugins:
  -ProSkillApi
  -ProMcCore
  -RoyaleEconomy


### latest.log

 https://pastebin.com/pbVxCaMv

### Anything else?

_No response_

**Comment by Travja** [comment]
I believe this to be caused by the fact that we were shading ProtocolLib into our plugin when building. The shading has been removed as it was only needed for LibsDisguises, which requires it in the first place. New builds should show this resolved.
