### ISSUE TITLE
[Bug]: Class HP reset on login 1.17.1

### ISSUE THREAD

**Issue by Phobiaphile** [promcteam/proskillapi#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time one of my players logs in, their HP is set to 20, despite everyone having a class with extra HP tied to the class. Their max HP is reapplied if a class reload is done, leaving them at 20/45 for example.

### Expected Behavior

The extra max HP should, and has previous to 1.17.1, been applied on login.

### Steps To Reproduce

1. Log in to server.
2. Check HP.
3. Class reload
4. Check HP again.

### Environment

```markdown
Server Software: paper-1.17.1-399
ProSkillAPI-1.1.7.6-ALPHA
ProMCCore-1.0.3.2-ALPHA
```

**Comment by goflishMC** [comment]
I was unable to reproduce this error, but we'll look into it.
