### ISSUE TITLE
[Bug]: Click Combo Dual Click

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using click combos, it will often count clicks 2 times instead of once.
This is only with left and right clicks as far as I know (shift always counted as one)

### Expected Behavior

Clicks having a delay before another click can be counted
Also it keeps counting clicks if you hold left or right click so if that can be removed or toggled off that would be great

### Steps To Reproduce

very simple, if you use click combos you will notice

### Environment

```markdown
- Server Software: paper 1.17.1 328
- ProSkillAPI Version: 1.1.7.4 ALPHA
- ProMCCore Version: 1.0.3.2 ALPHA
- Plugins:
```

**Comment by goflishMC** [comment]
I've had this same issue.

**Comment by Travja** [comment]
Should hopefully be resolved. In my testing, it wasn't causing any issues anymore. Will close when I receive confirmation from someone else.

**Comment by goflishMC** [comment]
confirmed to be fixed.
