### ISSUE TITLE
[Bug]: Stat Speed Mechanic 

### ISSUE THREAD

**Issue by RebelRanger** [promcteam/proskillapi#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While attempting to create a passive skill that increases movement speed by 1.5x times I've encountered a problem using the stat mechanic. Modifying movements speed by a multiplier of 2 has the desired effect. However when using decimal values such as 1.5 the movement speed doesn't change at all. When I tried changing the operation from multiply-percentage to add-number it will cause an error to be thrown in console. Here is the pastebin of the error when using the add-number operation. https://pastebin.com/E0G3N2Rs

### Steps To Reproduce

1. Create a skill that modifies movement speed using the Stat mechanic. Use multiply percentage and set the amount to a decimal like 1.5.
2. Run the skill.

### Environment

```markdown
- Server Software: paper-1.18.1-76.jar(happened with 1.17 as well)
- ProSkillAPI Version: ProSkillAPI-1.1.7.8-ALPHA
- ProMCCore Version: ProMCCore-1.0.3.3-ALPHA
- Plugins: BetonQuest, Chunky, Citizens, CurseOfVanishing, Essentials, LibsDisguises, MythicMobs, ProMCCore, ProSkillAPI, ProtocolLib, Skript
```

**Comment by Travja** [comment]
> When I tried changing the operation from multiply-percentage to add-number it will cause an error to be thrown in console. Here is the pastebin of the error when using the add-number operation. https://pastebin.com/E0G3N2Rs

Regarding the add mechanic, walk speed is a default of 0.2. If you're adding more to the value to increase it beyond the bounds of [-1, 1] it will throw an error. Just keep that in mind.
