### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JennaDiamonds** [promcteam/proskillapi#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When killing a Sentinel NPC, I receive the following error in console. I believe this error is preventing the player from receiving XP for ProSkillAPI. This happens when the sentinel is killed using skills, modified/unmodified weapons, bows and unarmed.

### Expected Behavior

Expected the death of the sentinel to be recognized by the plugin.

### Steps To Reproduce

1. Load the plugins mentioned.
2. create an NPC. /npc create <name>
3. change NPC trait. /trait sentinel
4. Kill the NPC.

### Environment

```markdown
Server Version:
CraftBukkit version 3363-Spigot-f65de01-e36f759 (MC 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
(Also tested on 1.17.1)
Plugins:
ProskillAPI - 1.1.7.9-ALPHA
ProRPGItems - 1.0.3.9-ALPHA
Promccore - 1.0.3.4-ALPHA
Sentinel - 2.4.0 build 446
Citizens2 -  2.0.29-b2428
```

### latest.log

https://pastebin.com/TR6Tz8KQ

**Comment by goflishMC** [comment]
This is the same as #117

**Comment by JennaDiamonds** [comment]
I don't believe so. They seem to take damage from using the skills I have built. What I'm describing is an issue related to the death of the NPC with sentinel trait.

**Comment by goflishMC** [comment]
> I don't believe so. They do take damage from using the skills I have built. What I'm describing is an issue related to the death of the NPC with sentinel trait. ProSkillAPI isn't recognizing the death and therefore does not award XP for the kill. It also does not trip the Kill Trigger.

my bad, I should have read that better.

**Comment by Travja** [comment]
I don't believe that the error is actually causing XP not to be given. I've just addressed the error itself, but it was throwing the error because it was treating the NPC death as a normal player, which they shouldn't be treated as such. If the problem of no XP persists, there may be another issue at hand.

**Comment by JennaDiamonds** [comment]
Beautiful. I'll dive further into the no XP issue and see what I can come up with. I just assumed it was related to this. Thank you for addressing this one, it's hard to find compatibility support for sentinels used in combat.

**Comment by Travja** [comment]
Closing this because of assumed resolution.
