### ISSUE TITLE
[Bug]: The Player is not registered as an ally when in a party

### ISSUE THREAD

**Issue by D0TORI** [promcteam/proskillapi#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the config.yml I have put parties-ally as true but in the game even though I was partied with another player I was able to inflict damage upon them. 

### Expected Behavior

When in a party it should also register you as a ally and nullify all damage between players.

### Environment

```markdown
- Server Software: Paper 1.16.5
- ProSkillAPI Version: 1.1.7.11
- ProMCCore Version: 1.0.3.5
- Plugins: Citizens, CrackShot, Essentials, EssentialsChat, EssentialsDiscord, HolographicDisplays, JShader, LibsDisguises, LuckPerms, Multiverse-Core, MythicLib, MythicMobs, NBTEditor, ProMCCore, ProSkillAPI, ProSkillAPIParties, ProtocolLib, Shopkeepers, SkinsRestorer, TAB, TriggerReactor, Vault, WorldEdit, WorldGuard
```

**Comment by Sentropic** [comment]
What form of damage did you use?

**Comment by D0TORI** [comment]
Skill Damage.
Also I used the skill that gives speed I to Ally, but the player in the party with me did not received the buff.

**Comment by goflishMC** [comment]
was it the damage mechanic @D0TORI

**Comment by D0TORI** [comment]
> was it the damage mechanic @D0TORI

yes
