### ISSUE TITLE
[Enhancement] Item Projectile + RPGItems Item Hints

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#192]
**Is your feature request related to a problem? Please describe.**

When using item projectiles and having item hints from RPGItems enabled, the items will glow and have a name SkillAPI#(number)
You can not disable this without breaking other items.

**Describe the solution you'd like**

RPGItems has an option to disable the glow by checking the item lore so putting a lore to the item projectile items that says "SkillAPI" and then adding it in the default config with a comment saying why it is there would be great.

**Describe alternatives you've considered**

Disable per material works but that will disable the custom item of the same material

**Comment by Travja** [comment]
For posterity's sake.. I've fixed the ignore rules for ProRPGItems. So you can add `SkillAPI#` to the list of ignored names for item hints and glow in the item_hints module settings.
