### ISSUE TITLE
Coin Steal / Money Steal Passives and Spells[Enhancement]

### ISSUE THREAD

**Issue by Svastojed** [promcteam/proskillapi#195]
**Is your feature request related to a problem? Please describe.**
Basically lets say you make a thief class, this way you could give them skills that steal money, or a merchant class can pay money to have items generated through a skill. 

**Describe the solution you'd like**
Just the abillity to make spells and passives that use/steal money.

**Describe alternatives you've considered**
Just not there yet.

**Additional context**
I Would really appreciate it.

**Comment by goflishMC** [comment]
For a money mechanic, this is what I've come up with

<pre>
New Mechanic: Money

options
type: Money/Multiplier/Percent Left/Percent Missing # if set to "money" is flat amount
Value Take: amount
Value Give: amount
silent: true/false # cancel skill message to target
can-be-negative: true/false # If true and player does not have enough to cover the amount, they will go negative
</pre>

Can you explain in more detail about exactly what options you would need for a merchant class? Is it a mechanic, skill, targeter, etc and what options would it need to have?

I also came up with this for a money condition:

<pre>
New Condition: Money

Type: Money/Percent/Difference/Difference Percent # if set to money, then it would be a flat amount
Min Value:
Max Value:
</pre>

**Comment by Svastojed** [comment]
Basically a merchant would have a skill (example): Blessed Ports
Hed pay
Mechanic:
Money
Value Take 
500

for example and then hed get specified items in exchange.

Yeah that looks good goflish

**Comment by goflishMC** [comment]
This feature has been added.
