### ISSUE TITLE
[Bug]: can't disable skillbar

### ISSUE THREAD

**Issue by monleak** [promcteam/proskillapi#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried disabling the skill bar but it didn't work. If enable is set to false, it will still receive items.
Paper 1.16.5 

### Environment

```markdown
- Server Software:  Paper Spigot 1.16.5
- ProSkillAPI Version: 1.1.7.11
- ProMCCore Version: 1.0.3.5
- Plugins:
```

**Comment by Travja** [comment]
Sorry for the delayed response here. Is this still an issue? I haven't had issues with it myself. Could you provide more detail on your configuration and what you're doing?
