### ISSUE TITLE
[Enhancement] Dynamic Editor Comments

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#204]
**Describe the solution you'd like**

A new option inside the editor that allows us to put comments in the skill.
It can be very useful when making a complicated skill and you need to either put notes in it to not forget what part does what or you need to separate some parts of the skills for the sake of better organization.
It can also be helpful to explain what part of the skill does what if you try to publish it online.

**Comment by goflishMC** [comment]
I'm thinking about a new condition called Comment, but doesn't actually check for anything. Do you think it needs the "add child" with it?

**Comment by goflishMC** [comment]
can you give an example of where the comment would go? exactly how where would this feature be added to the editor

**Comment by lordsrubka5** [comment]
Well, thats the thing. Its not like its a trigger condition or mechanic directly. Its goal is something of utility to make the "code" of the skill easier to tell apart. It can either have its own group or be inside mechanic. It should also be very clear that its a comment once put inside the skill by being a different color then the rest? If possible that is. The goal is just to put some space between mechanics and group them up in larger skills so we know aprox what each part does without clicking on each value mechanic or particle mechanic to know what it does.

**Comment by goflishMC** [comment]
@lordsrubka5 Are you talking about a "Comment Mechanic" Would this mechanic have child options? 

Can you show with an image/screenshot with exactly where and how you want to see these comments?

**Comment by Travja** [comment]
@lordsrubka5 Would you want this in the form of a mechanic that only has effect on the editor? Or would it be better to have some sort of `note` field under all components on the editor that, if you fill something in, will display when looking at the general overview of the skill?

**Comment by lordsrubka5** [comment]
Not sure. Im using Delay mechanic with 0 time and it works great for me. It has no impact on the skill and it allows me to group other blocks into it and to colapse them. I can also add a little note in the key section. You can close this or keep open for future if you plan to add this regardless.
