### ISSUE TITLE
[Enhancement] Block/Mining Feature

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#207]
As discussed in discord: 

This would allow to setup a mining skill that can break blocks in a cube or sphere
1. Block break trigger
2. Block Target (new target cloned from appropriate target)
3. Mine mechanic (new mechanic, destroys blocks at the target, dropping them)

Sentropic: "The mine mechanic could have options to break blocks in a cube or sphere of configurable size, and selecting only blocks of the same type as the origin, or any other block"

Also add option to cancel all drops, so that only the blocks break, but nothing drops.

**Comment by Sentropic** [comment]
That should be all of it. I'll push the changes to the editor once this feature is released in a dev build.
