### ISSUE TITLE
[Bug]: Mechanics[Stat] Will turn health into 20

### ISSUE THREAD

**Issue by YYYYYYase** [promcteam/proskillapi#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Stat] is not affected    modify-health    , will turn health into (classless-hp)

config.yml

Classes: 

   Whether or not to use SkillAPI's health system
  modify-health: 'false'

   The default health for players without a class

  classless-hp: '20'

After use, if the health value is greater than 20, it will be set to 20
[skill 3.zip](https://github.com/promcteam/proskillapi/files/7822148/skill.3.zip)

### Environment

```markdown
- Server Software:paper-1.16.5-428
- ProSkillAPI Version:ProSkillAPI-1.1.7.12-ALPHA
- ProMCCore Version:promccore-1.0.3.5-ALPHA
- Plugins:
```

**Comment by Travja** [comment]
The `modify-health` option in the config actually doesn't do basically anything. In fact, having it false may actually be causing the issue you've described if I follow correctly. Try setting it to true. The other things to consider are the `GUI.old-health-bar` setting and the `GUI.force-scaling` setting.

**Comment by YYYYYYase** [comment]
I tried like you said，But it's still there ：（
I use both Proskillapi and MMOItems，My inference is: When using this skill，
Skillapi wrong to think player's Max health is Class's Max.   This bug can be raised if the maximum health is raised through another plugin

**Comment by Travja** [comment]
This is just interesting because we haven't had any other reports of this. If you could zip up your skillapi files and send them over, we can give it a good test.

**Comment by YYYYYYase** [comment]
Of course, they are here, and thank you for paying attention to my question
[skillapi files.zip](https://github.com/promcteam/proskillapi/files/7995202/skillapi.files.zip)

**Comment by Travja** [comment]
I've just tested this out. Not sure if it has anything to do with the updates to various health-related things that have been happening lately, but with your skill, I did not run into any issues. Closing the ticket.
