### ISSUE TITLE
[Enhancement] Mechanic Triggers for new Triggers

### ISSUE THREAD

**Issue by RebelRanger** [promcteam/proskillapi#209]
With the addition of new triggers(which are amazing) it would be really nice if the mechanic "trigger" which listens for triggers on the target would get updated with the additional triggers. Currently it can only use older triggers and doesn't include the new ones. 
For example if I cast a skill it could listen for "left click" trigger for 5 seconds. On a left click it would fire off a projectile. 

**Describe alternatives you've considered**
The example skill I listed above could technically be done by adding a flag to the caster when cast and having the skill trigger the projectile whenever the player left clicked with the flag set. However this does add a bit more complexity to a rather basic skill.

**Comment by goflishMC** [comment]
Trigger Mechanic needs the following triggers added to this mechanic.

Block Break
Block Place
Cast
Crouch
Drop Item
Fishing
Fishing Bite
Fishing Fail
Fishing Grab
Fishing Ground
Fishing Reel
Item Swap
Left Click
Move
Right Click
