### ISSUE TITLE
[Bug]: Formats Break Icon Keys in Lore

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If there are formats in front of the icon keys in skills lore, it will break the icon key and making it display 0
Formats include:
 - &k Random texts
 - &l Bold
 - &m Strikethrough
 - &n Underline
 - &o Italic

Normal colors work fine.

### Expected Behavior

To work like it does at first load/reload and not to change the config on its own on second load/reload.

### Steps To Reproduce

- Make a skill and setup an Icon key to display something in the lore
- Add a formatting in front of it
![image](https://user-images.githubusercontent.com/74104790/148703198-8a5c1fb0-ca34-4218-9409-9ffd246b0132.png)
- Save the file and reload the plugin and check the lore
![image](https://user-images.githubusercontent.com/74104790/148703212-6bae29b2-9a20-4441-b5a3-1b951d84ca4a.png)
- Works fine! Now reload the plugin again
![image](https://user-images.githubusercontent.com/74104790/148703224-c657e195-97fc-410c-99f1-0d1718fc1cb5.png)
- And finally refresh the skill yml file and check the Icon key 
![image](https://user-images.githubusercontent.com/74104790/148703238-2535f77a-1195-4505-bb7d-dc0cdb1f03d7.png)

### Environment

```markdown
- Paper 1.17.1 328
- ProSkillApi 1.1.7.11 ALPHA
- ProMCCore 1.0.3.5 ALPHA
```

**Comment by Travja** [comment]
Just fixed this, but it's important to note that any duplicated color codes would cause this issue. So even doing `&4&c` would cause `&c` to be left over. Typically this, we only double up color code stuff when applying formatting, but it would happen either way. But this should be addressed now regardless!
