### ISSUE TITLE
[Bug]: Stealing Icons From GUIs

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You can glitch out icons from GUIs.
To do it you first need to shift click it to level it up or to right click it for downgrade.
In the split second that the icon is in your inventory you need to close the menu with escape button.
When closed the icon will still be in your inventory and it is not a visual glitch, you can move it around, drop it and all other stuff.
This is easier to pull off with higher ping.

### Environment

```markdown
-
```

**Comment by Travja** [comment]
Are all guis affected or only some?

**Comment by lordsrubka5** [comment]
I tested with attributes and skills but I feel like class profess works too. I don't know how to use the class details one

**Comment by Travja** [comment]
Looking at the code, it appears that this should never happen. Programmatically, if this is an issue, it should logically be an issue for any plugin that uses inventories as a GUI for the user. If the programming lines up the way it should, any time you click in the inventory at all, it'll cancel the click and MC/Spigot should handle making sure that the item is not left in your inventory.

What version of Spigot are you using? Have you tried other versions?

**Comment by lordsrubka5** [comment]
Minecraft treats inventories differently in creative mode so the event that cancels taking items from GUIs is not working very well in it. Confirmed on multiple server versions with multiple people.

**Comment by lordsrubka5** [comment]
Forgot to mentions that this is an issue for all plugins not just skillapi
