### ISSUE TITLE
[Enhancement] Total Invisibility

### ISSUE THREAD

**Issue by KURAMAAA0** [promcteam/proskillapi#215]
I want the possibility to turn players completely invisible.
Currently we can use the invisibility potion mechanic but if we hold an item or have an armor they’re obviously still visible.

An « Invisible » mechanic that makes a player totally invisible (no held items or armor visible)

**Comment by RebelRanger** [comment]
A fairly easy workaround for this is to use the libsdisguises plugin and disguise the player as something like an air block. Though total invisibility would be nice!

**Comment by xMystik** [comment]
After some testing with the new invisibility feature I've noticed that it works alright for the most part but there are times that the invisibility effect is finished and other players can see you without wearing any armor, although you do.
