### ISSUE TITLE
Else node

### ISSUE THREAD

**Issue by TheVirusUk** [promcteam/proskillapi#218]
Else node on the editor does not seem to do anything. i have a flag set to true and upon rightclick if its false something else should happen but never does.

**Comment by Travja** [comment]
Can we verify this @goflishMC?

**Comment by goflishMC** [comment]
> Can we verify this @goflishMC?

I've used the else condition many times recently with no issues. they most likely had set it up wrong.

**Comment by Travja** [comment]
This is old and most likely not an issue then. So @TheVirusUk, before reopening this, please ask for help on our Discord!
