### ISSUE TITLE
[Bug]: skills not showing up in gui

### ISSUE THREAD

**Issue by Shavick** [promcteam/proskillapi#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

skill not showing up on the gui after i have paired it with the class it goes to.

### Expected Behavior

skill should pop up in gui if i formated it exactly like the one that works

### Environment

```markdown
- Server Software: shockbyte
- ProSkillAPI Version: latest
- ProMCCore Version: latest
- Plugins:
```

**Comment by goflishMC** [comment]
You need to put the version numbers, not just latest.

**Comment by goflishMC** [comment]
Did you add it with /class customize

**Comment by Shavick** [comment]
sorry about that, i didnt have to do /class customize last time i added a heal spell though. do i have to do that even if i have it linked to the class?

**Comment by goflishMC** [comment]
Yeah, you need to add it to that menu anytime you make a new skill
