### ISSUE TITLE
[Bug]: Level limit bug

### ISSUE THREAD

**Issue by jungwuk-ryu** [promcteam/proskillapi#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

The player can attack an entity with level limited sword. (He has not met conditions)

### Expected Behavior

The player can't attack an entity with level limited sword. (He has not met conditions)

### Steps To Reproduce

**_1. Set "drop-weapon" to "false" in config_**
2. Set "lore-level-text" in config
3. Set your items lore
4. Attack an entity

### Environment

```markdown
- Server Software: git-Paper-1618 (MC: 1.12.2)
- ProSkillAPI Version: 1.1.7.14-ALPHA
- ProMCCore Version: 1.0.3.5-ALPHA
- Plugins:
```

### latest.log

X

### Anything else?

When drop-weapon is true, It works fine because of [this](https://github.com/promcteam/proskillapi/blob/ba30f8386708d67d728ccbeab36be1ed220253cc/src/main/java/com/sucy/skill/data/PlayerEquips.java#L126)

By the way when drop-weapon is false, the plugin will do nothing. (Plugin should update handHeldItem)
So, [this line](https://github.com/promcteam/proskillapi/blob/ba30f8386708d67d728ccbeab36be1ed220253cc/src/main/java/com/sucy/skill/listener/ItemListener.java#L249) works wrongly. ([handHeldItem](https://github.com/promcteam/proskillapi/blob/ba30f8386708d67d728ccbeab36be1ed220253cc/src/main/java/com/sucy/skill/data/PlayerEquips.java#L73) is incorrect.)

I think, we should add "this.handHeldItem = to;" to [this line.](https://github.com/promcteam/proskillapi/blob/ba30f8386708d67d728ccbeab36be1ed220253cc/src/main/java/com/sucy/skill/data/PlayerEquips.java#L132)

I apologize for my bad English 😢

**Comment by lordsrubka5** [comment]
As of right now, restricting items to classes only means that you will not get any attribute stats from that item but still can use the base item like if it was just a normal vanilla item. However if its armor then you can not equip it (though I think they didn't fix shift clicking it)

![image](https://user-images.githubusercontent.com/74104790/151674854-0175b448-430f-4d58-945c-6db93905c5b1.png)

**Comment by jungwuk-ryu** [comment]
Thank you @lordsrubka5 
But I don't understand why [this line](https://github.com/promcteam/proskillapi/blob/ba30f8386708d67d728ccbeab36be1ed220253cc/src/main/java/com/sucy/skill/listener/ItemListener.java#L250) exists.
I think it'll never be called.

**Comment by goflishMC** [comment]
@jungwuk-ryu you need promccore 1.0.3.6
