### ISSUE TITLE
[Bug]: Bonus health getting reset when changing hot bar slots

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

This does not occur when in OP.

When I have bonus health from any other source, when I change hot bar slots the bonus health is lost like as if I took damage. (my max health doesn't change)

### Expected Behavior

When changing hotbar slots, my hp should stay the same.

### Steps To Reproduce

Easiest way to test is to add health to an item with the rpgitems command /qrpg set stat MAX_HEALTH 500

then equip the item, do /heal and then change hot bar slots.

This issue did not happen when I removed the skillapi plugin from my server.

### Environment

```markdown
- Server Software: Paper 1.18.1
- ProSkillAPI Version: 1.1.7.14
- ProMCCore Version: 1.0.3.6
- Plugins: https://i.imgur.com/9n1pV5r.jpeg
```

**Comment by Travja** [comment]
Okay, interestingly enough, this appears to happen only when switching to slots in your hotbar that have an item in them. Empty slots don't do this. Will be doing more testing to see if I can track this down.
