### ISSUE TITLE
[Bug]: The point adding interface cannot display the remaining points in real time

### ISSUE THREAD

**Issue by luoxiawuchen** [promcteam/proskillapi#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Steps To Reproduce

1、/class attr
2、
![image](https://user-images.githubusercontent.com/64759847/153193623-ccb1ab57-2c15-4dc1-8474-aaee78681788.png)
3、
![image](https://user-images.githubusercontent.com/64759847/153193645-ab08b30f-b507-42e4-8fc6-ecbfd63ef61b.png)

### Environment

```markdown
- Server Software: Paper Spigot 1.16.5
- ProSkillAPI Version: 1.1.7.14-ALPHA
- ProMCCore Version: 1.0.3.6-ALPHA
- Plugins: promccore-1.0.3.6-ALPHA、proskillapi-1.1.7.14-ALPHA、ProSkillAPIParties-1.0-snapshot
```

**Comment by Travja** [comment]
I'm not sure what you're asking here and everything seems to be working as intended. If you would like to provide more detailed information of what isn't functioning as it should, feel free to reopen this issue.
