### ISSUE TITLE
[Enhancement] Cast Bind Scrolling

### ISSUE THREAD

**Issue by Nazir-Ali** [promcteam/proskillapi#238]
**Is your feature request related to a problem? Please describe.**
Sometimes combos and other cast methods can be unreliable, so for consistent casting, its better to bind a spell to an item and right click to cast it, but then your inventory can get "cluttered" as you try to avoid accidentally casting on a right click

**Describe the solution you'd like**
2 Part Solution:
1. Allow any amount of skills to be bound to an item, on left click the item would switch to the next skill in the list, displaying the skillname either in the chat or in the exp bar, and on right click the skill would be cast. This would allow bind-casting to only use up a single inventory space
2. Bound skills are bound only to that specific instance of the item, so if you have 2 stone swords in your inventory for example, and you bind a skill to one, it does not bind to the other, that way you can have duplicate items, one with skills, one without.

Functionally it would be a more customizable mix between the normal binding method and the bar casting method

**Describe alternatives you've considered**
I feel like that is the only reasonable way to go about it, I know all of casting is eventually getting an overhaul so the other methods may be nicer to use in the future, but I feel like this one puts a lot of control and customizability in the players hands

**Additional context**
N/A

**Comment by Travja** [comment]
Binding has been reworked to work mostly like this. Additionally, you can add multiple skills to items via ProRPGItems.
