### ISSUE TITLE
[Bug]: Broken Move Speed Attribute 1.16.5

### ISSUE THREAD

**Issue by Svastojed** [promcteam/proskillapi#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

[Bug]: Since the  last update  that correct the move speed value the attribute  is broken putting it at 0.04 to start with  still gives you default speed which is around 0.16.

### Expected Behavior

Like  Races of Thana or other plugins that  use the correct default value. I currently have 1  point set to 0.0005 move you can gain up to 0.01. so i set the beginning points  to varying amounts  to differentiate the class movement speeds. however a dwarf who should move 0.005 is  still moving like 0.16

### Environment

```markdown
- Server Software:1.16.5
- ProSkillAPI Version: Latest Public
- ProMCCore Version: Latest Public
- Plugins: ProSkillApi Partys
Its a testing setup without any other plugins.
```

**Comment by Travja** [comment]
So you're saying that the initial movement speed setting is broken, or the incrementing bit of it is broken?

**Comment by Travja** [comment]
```yaml
  stats:
    move-speed: 'a*0.25+1*v'
```
I used this, and it appears to be working just fine.

**Comment by Svastojed** [comment]
mines  move-speed: '(a*0.0001)+v' that  should give 0.001 movement speed if i give one starting point but i move the regular 0.16

**Comment by Svastojed** [comment]
appereantly  it works fine for multiplayer but it might be a problem with static points.
