### ISSUE TITLE
[Enhancement] Plugins Support [ RPG Player Leveling ]

### ISSUE THREAD

**Issue by CaoCuong12** [promcteam/proskillapi#25]
I want ProRPGItems
Plugins Support [ RPG Player Leveling ]
https://www.spigotmc.org/resources/rpg-player-leveling.11096/

I want the potential points of the RPG Player Leveling Plugins, which will increase the overall stats with ProRPGItems
Can you support this plugin?
I really need its [potential score] feature

This is one of the necessary plugins for the RPG server

**Comment by goflishMC** [comment]
> I want ProRPGItems
> Plugins Support [ RPG Player Leveling ]
> https://www.spigotmc.org/resources/rpg-player-leveling.11096/
> 
> I want the potential points of the RPG Player Leveling Plugins, which will increase the overall stats with ProRPGItems
> Can you support this plugin?
> I really need its [potential score] feature
> 
> This is one of the necessary plugins for the RPG server

you need to post this suggestion here: https://github.com/promcteam/prorpgitems/issues
