### ISSUE TITLE
[Enhancement] /skill bind skillname ?

### ISSUE THREAD

**Issue by Svastojed** [promcteam/proskillapi#251]
**Is your feature request related to a problem? Please describe.**
Expand the Skill Bind Menu by a additional   option. 
**Describe the solution you'd like**
For Example if i type in /skill bind skillname a
The skill would be bound to  the a button
**Describe alternatives you've considered**

**Additional context**

**Comment by Travja** [comment]
This sort of already exists with combos. And the hard part about it is, there are only certain keypresses that can be detected. These include things like pressing 'Q' to drop an item, right/left click, sneaking with 'Shift', swapping an item to your shield slot with 'F', etc. Basically, we can only detect keypresses that fire an event.

In context with your example directly, we could sort of detect a keypress for 'A' by listening to the move event and checking the movement vector in relation to where they're looking, but it's more complicated than I want to deal with at the moment. Additionally, binding skills to movement keys would be unwise as it would interfere with movement.
