### ISSUE TITLE
[Bug]: Item Projectile in Editor

### ISSUE THREAD

**Issue by 3Lord3** [promcteam/proskillapi#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Now creating "Item Projectile" mechanics in Editor, regardless of the "Material" value, the projectile will be a jack light.
![image](https://user-images.githubusercontent.com/62335161/154858154-def745a0-0b66-4916-a2b1-0cd708a73f29.png)

As I was able to figure out, this happens because the item type should be "Item" and not "Material". 
The SkillAPI wiki has a working example (Skill "Bolas") that uses the type "Item". I changed this value in my skill and it worked.
[Shrapnel (Incorrect).txt](https://github.com/promcteam/proskillapi/files/8104697/Shrapnel.Incorrect.txt)

### Expected Behavior

The Dynamic Editor must use the correct type for the item
![image](https://user-images.githubusercontent.com/62335161/154858167-56d3c457-8701-461b-858f-7886e9c6fa5e.png)
[Shrapnel (Correct).txt](https://github.com/promcteam/proskillapi/files/8104699/Shrapnel.Correct.txt)

### Steps To Reproduce

1. Create skill with "Item Projectile" mechanic in Editor
2. Change the value of "Material" to any item
3. Try using the skill

### Environment

```markdown
- Server Software: Paper version git-Paper-205 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 36a1650)
Previous version: git-Paper-101 (MC: 1.18.1)
- ProSkillAPI Version: 1.1.7.14
- ProMCCore Version: 1.0.3.6
- Plugins: LuckPerms, ProMCCore, ProRPGItems, ProSkillAPI
```

### Anything else?

[Bolas.txt](https://github.com/promcteam/proskillapi/files/8104709/Bolas.txt)

**Comment by Travja** [comment]
Ah! That should be a quick fix on the editor. @Sentropic do you want to address this?

**Comment by lordsrubka5** [comment]
wait its still not fixed?
damn I though he said he would fix it

**Comment by Sentropic** [comment]
For it to work properly you must use the latest dev build we published on Discord!

Some option names were changed for parity and code efficiency, which means newly created skills containing certain mechanics will need the latest build. But old skills are still fully functional in the new versions.
