### ISSUE TITLE
[Bug]: Item Projectile Trajectory

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#257]
**Is your feature request related to a problem? Please describe.**
Item projectile trajectory is weird right now. It only despawns when hitting a floor.
This means that as long as its not a floor it will keep going making it possible to
make some bouncing effects when items slide along walls. And yes, they will still
trigger the effect if they land on the enemy.

**Describe the solution you'd like**
An option if the projectile should fully stop on impact

**Comment by Sentropic** [comment]
Done. Should come in the next patch! Do note that it becomes somewhat unreliable at high speed (3 blocks/tick or higher), so if you need something very fast, consider using Projectile Mechanic or straight up Location Target instead.
