### ISSUE TITLE
[Bug] Dynamic Editor

### ISSUE THREAD

**Issue by BeanOat** [promcteam/proskillapi#26]
**The Bug**

- When I try to start a class or skill, it doesn't let me click the button to make one. When I click it, nothing happens. I am using Google Chrome. I found a way to get the skill to work by pressing delete and then it'll let me add more, and its fine, but what use are the skills if I can't make a class for them. Love this plugin by the way, this plugin being outdated is the sole reason I stopped making my MMORPG, so I really hope you can get back to me with an answer so I can start this back up!

**To Reproduce**

1. Go to 'https://www.promcteam.com/editor/'
2. Click on 'Classes Tab, and then New Class'
3. See Error

**Expected behavior**

- It won't allow you to view "Class 1" that's already there, or make a new one. 

**Additional Info**

- I'm using Google Chrome, I'm not sure if that's the issue or if the page is just currently bugged.

**Comment by SparkGNRK** [comment]
The editor is working good for me in google chrome, try to clear cache for this page since we changed something in the editor. (When clearing the cache you lose all the data stored inside, click on "Backup All Data" first)

**Comment by goflishMC** [comment]
Also, make sure you update chrome https://support.google.com/chrome/answer/95414?co=GENIE.Platform%3DDesktop&hl=en
