### ISSUE TITLE
[Bug]: SQL data not syncing correctly

### ISSUE THREAD

**Issue by MuRDea** [promcteam/proskillapi#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When I switch bungee class levels and exp not synce

this is my config.yml

Saving: 

  # Whether to auto save data periodically
  auto-save: 'true'

  # How often to auto-save in minutes
  minutes: '30'

  # Whether to use an SQL database to save
  sql-database: 'true'

  # Details for connecting to the database
  sql-details: 
    host: 'localhost'
    port: '3306'
    database: '116class'
    username: 'root'
    password: '123'
    # Time to wait on loading data from the SQL database in ticks.
    # Can be used to give time for other servers to synchronize data. Note:
    # this does not apply when loading player data on server startup since
    # players wouldn't be coming from another server.
    delay: '0'

### Expected Behavior

i hope fix this bug

### Steps To Reproduce

I on the lobby server switch rpg server levels and exp not synce

### Environment

```markdown
- Server Software: Paper 1.16.5
- ProSkillAPI Version: 1.1.7.15-0930442
- ProMCCore Version: 1.0.3.7-0930442
- Plugins: PlaceholderAPI-2.11.1 、promccore-1.0.3.7-0930442 (1)、proskillapi-1.1.7.15-0930442 (1)、ProtocolLib
```

**Comment by Travja** [comment]
This is one of those bugs that seems slightly fleeting and inconsistent. I can say that for the most part, the people I've heard that have used SQL for data storage haven't appeared to have too many issues. In order to test this, I'll have to get a proper set up of my own running.

In the mean time, if you do `/class reload` does it update your information at all?

**Comment by Travja** [comment]
I'm going to close this for the time being until other reports come in for this. It's not that I am refusing to fix this, but rather that it doesn't seem to be much of an issue. Please let me know if anyone finds any other issues like this.
