### ISSUE TITLE
[Enhancement] World Guard Region Condition

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#263]
**Describe the solution you'd like**
There is a file called WorldGuard.yml in SkillAPI that lets you disable
casting skills and gaining exp fully in world guard regions, however
there is no way to select what skills you want to be disabled.

This can be good if you want to disable some skills in some areas
from doing some effects or changing their effect based on where
the player is (maybe different damages and effects for pve and pvp).
The workaround would either be for that location to be in different
world or using biomes like void to separate them from the rest.
Not really needed asap but it would be nice to have in the future.

**Comment by goflishMC** [comment]
#381
