### ISSUE TITLE
[Enhancement] Flag Stacking

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#264]
**Describe the solution you'd like**
Currently you can only have a flag type on or off, it would be nice
to have an option to have them stackable in quantity.

Using attributes for this is possible only for players but not on mobs

**Comment by Sentropic** [comment]
Wouldn't values work for this?

**Comment by lordsrubka5** [comment]
Are values global or only saved within a specific skill? Theres not much info about that

If they are global there is no need for for this enhancement since all I wanted was a global
way for multiple skills/people to stack one value/flag

**Comment by lordsrubka5** [comment]
> If they are global there is no need for for this enhancement since all I wanted was a global
way for multiple skills/people to stack one value/flag

yeah seems like thats how values work so this is pointless
