### ISSUE TITLE
[Enhancement] Skill Item Cooldown Animation

### ISSUE THREAD

**Issue by Storexo** [promcteam/proskillapi#269]
**Describe the solution you'd like**
When using a skill initiate item cooldown for that item in the corresponding skill slot. The item cooldown refers to the Ender Pearl-cooldown animation usable with player.setCooldown. Been trying to set it up myself using the updateCooldown() but you are unable to start item cooldown async. Would be a great addition/alternative to the "amount of items = cooldown" that currently exists. 

**Describe alternatives you've considered**
Been using a work-around when you use another plugin that can set item cooldowns on specific items and then use the command-mechanic inside skills in SkillAPI. However, when using many skills you need one command for each skill since they have different cooldowns. 

**Additional context**
https://media.giphy.com/media/P4gA7trK08KEgThyAR/giphy.gif

**Comment by Sentropic** [comment]
Indeed this is a duplicate of #249
