### ISSUE TITLE
[Enhancement] Chat Trigger

### ISSUE THREAD

**Issue by joosii** [promcteam/proskillapi#27]
Hi! 
I had some few ideas after working on some stuff.

Condition name:  **Chat**
I think it's pretty self explanatory, just a condition that triggers mechanics when the target says something in chat.

And another idea I had was a mechanic that lets you teleport to the player, currently I'm trying to make an ability that teleports everyone near to another player called Group Teleport. 
I'm not sure if these are possible but it'd be great, thanks devs for the handwork :)

**Comment by SparkGNRK** [comment]
You can already teleport using warp mechanics, in your case it would be "warp target".

But the Chat condition could be something good.
