### ISSUE TITLE
[Enhancement] multiple damage trigger 

### ISSUE THREAD

**Issue by thuan782004** [promcteam/proskillapi#279]
**Is your feature request related to a problem? Please describe.**
I'm trying to make a passive skill that can produce different effects when taking different types of damage. However I cannot create more than one card took skill damage 

**Describe the solution you'd like**
Allows creating triggers of the same type at the same time

**Comment by Travja** [comment]
We've had the ability to add multiple of the same triggers for a while now. Should be able to work for what you would need.
