### ISSUE TITLE
[Bug] Class/Skills Loading Error

### ISSUE THREAD

**Issue by BeanOat** [promcteam/proskillapi#28]
**Bug

I'm not sure why this started happening, because it wasn't happening prior, but out of nowhere, everytime I try to load up the server, my classes won't load their skills, and it causes the classses to be there, and usable, but with 0 skills, it just gets rid of all the skills. This wasn't a problem, and all of a sudden started happening even though I hadn't changed anything or added any plugins, etc. Very strange. 

**Steps to reproduce the behavior:

Not sure, I'm not even sure how it happened, it just started becoming an issue, and nothing I do fixes it.

**Latest Log: 

https://pastebin.com/H72cyXwS

Versions

-  Spigot Version: 1.16.5, same error on 1.16.1
 - Plugin Version: Latest Version

**Comment by goflishMC** [comment]
1. Download your classes and skills from the editor and then stop your server.

2. Make a backup of your dynamic files on your server, and then delete the dynamic folder.

3. Start your server, so that it recreates the dynamic folder

4. Upload the classes.yml and skills.yml to the dynamic folder and then do /class reload

Let me know if your skills still do not load after following those steps

**Comment by BeanOat** [comment]
speaking of /class reload, that doesn't work either

**Comment by BeanOat** [comment]
i'll make a bug of that as well

**Comment by BeanOat** [comment]
it didn't work, still the same issue by the way, just says the class has no
abilities

**Comment by BeanOat** [comment]
not sure why this is happening, i'm just going to reset my entire skillapi
file and just see if that works

**Comment by BeanOat** [comment]
okay yeah I fixed it, I must've messed up a config setting. All good now,
/class reload still never works tho, maybe if I switch to paper spigot
it'll work, I'll let you know, and the editor is still bugged but if I
reset my cache and cookies and reload the page it usually fixes it, still
glitchy tho

**Comment by goflishMC** [comment]
We just released a new build, make sure you have this: https://promcteam.com/resources/proskillapi-custom-classes-skills-with-online-editor.7/

and this: https://promcteam.com/resources/mccore.8/

**Comment by goflishMC** [comment]
If the build doesn't fix your /class reload issue, you can reopen this.
