### ISSUE TITLE
[Bug]: Potion Condition Doesn't Work

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

![image](https://user-images.githubusercontent.com/74104790/164418195-8f1210f6-6dad-404b-91b8-c4034683bec2.png)
As shown here, my skill has a potion condition to not trigger when players have night vision 2 (in Vanish)
and that works great, when player has any level other than 2 of night vision the skill works and when the
player has level 2 effect it doesn't. However the issue is that if a player has **ANY** other potion effect,
regardless of the potion level, the skill will not trigger.

### Expected Behavior

For the condition to work as intended

### Steps To Reproduce

make a condition to only check one potion
apply any other effect and test

### Environment

```markdown
-
```

**Comment by Travja** [comment]
Could you explain this a little bit more for me? Am I understanding this correctly? 1. The levels don't match properly and 2. If the player has any _additional_ potion effects, it doesn't detect the night vision properly?

**Comment by lordsrubka5** [comment]
For me right now there is a condition for a skill to not work if a player has night vision 2 effect.
If a player has night vision 1 or 3+ it works. If a player has night vision 2 it doesn't work which is the intended part.
However if a player has **any other** potion effect, regardless of level,  it will count it as if its a night vision 2 making the condition not trigger. Aka if I give myself speed 1 it doesn't work. I did not test if it works with night vision 2 and any other potion effect.

**Comment by Travja** [comment]
Oh okay, so the intended effect is that the child effects are only prevented if the user has night vision 2. Any other set of potions and whatnot should be allowed.

**Comment by lordsrubka5** [comment]
Yes. It messes it up when it uses any potion effect that is not night vision. Not sure if its just because it has weird way of interacting with other potions that are not mentioned or if its because of the "Not Active" setting
