### ISSUE TITLE
[Bug] getting error when execute command /class reload

### ISSUE THREAD

**Issue by ThunPao** [promcteam/proskillapi#29]
**Describe the bug**
getting error when reloading plugin using "/class reload" command

**To Reproduce**
1. Joined the game
2. execute player command: class reload
3. Plugin said: An internal error occurred while attempting to perform this command
4. Player Data couldn't save
**Expected behavior**
-

**latest.log**
https://pastebin.com/er9U1Rfr

**Versions (please complete the following information):**
-  Spigot Version:
- 1.16.5
 - Server Version:
 - purpurclip-1.16.5-1086
 - Plugin Version
ProSkillAPI-1.1-ALPHA
MCCore-1.1-ALPHA

**Additional info**
-

**Comment by goflishMC** [comment]
This is fixed now: https://promcteam.com/resources/proskillapi-custom-classes-skills-with-online-editor.7/
