### ISSUE TITLE
[Enhancement] Add F button to start or disable shortcut skill "combo" mode

### ISSUE THREAD

**Issue by ReverseAllen** [promcteam/proskillapi#291]
I think it is possible to add.
when pressing the F button, Enable or disable COMBO mode skills.
Let player avoid accidentally triggering skills when it is not necessary.
Title text will be displayed when it is turned on or off, and the current status message will be notified to the player.

**Comment by lordsrubka5** [comment]
Oh, I just thought of a workaround that I'm going to use for now. Making a skill that can be casted either with a Item Swap trigger for F button or a cast command with an alias that gives you a flag. If you already have a flag when casting it would turn it off. Then you can add a flag condition for the said flag on all skills to not trigger if the flag is active.

**Comment by Travja** [comment]
As part of the recent casting rework, we have also included combo starters that you can configure through the editor.
