### ISSUE TITLE
[Enhancement] Available Skill Points Placeholder

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#292]
**Describe the solution you'd like**

There is a placeholder for available attribute points but not for skill points.
This is very useful when not able to use {points} placeholder due to GUI textures.

**Comment by k437u** [comment]
You can use textures one per class tho

But placeholders would be extremely useful. The PlaceholderAPI expansion for legacy skillapi version doesn't work with proskillapi. This includes things such as %sapi_value:<key>%, %sapi_skill_points:<group>%, %sapi_combo% a lot of people would find these very useful

**Comment by Travja** [comment]
`%sapi_default_currentavailableskillpoints%` and `%sapi_player_<group>_availableskillpoints%`

**Comment by lordsrubka5** [comment]
My guy chose the longest possible name for the placeholder. Just get rid of currently available in the name its useless and just call it sapi default skillpoints

**Comment by Travja** [comment]
Lol. I just cloned the placeholder for attributes and changed it to skills :P

**Comment by Sentropic** [comment]
Just stumbled upon this thread
> My guy chose the longest possible name for the placeholder. Just get rid of currently available in the name its useless and just call it sapi default skillpoints


```
            if (identifier.equals("default_currentavailableskillpoints")
                    || identifier.equals("default_skillpoints")
                    || identifier.equals("default_currentlyavailablesuperawesomeultramegagigaamazingskillpoints")) {
                return String.valueOf(data.getMainClass().getPoints());
            }
```

XD
