### ISSUE TITLE
[Enhancement] Attribute Force Downgrade Without Refund

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#295]
**Describe the solution you'd like**

A way to either forcefully remove players attribute points without a refund or a way to subtract players available attribute points.

**Comment by lordsrubka5** [comment]
Retyping context

A way to adjust players attributes positively and negatively without affecting players attribute points (since admin command attribute downgrade gives the player his attribute points back)

**Comment by Sentropic** [comment]
`/class forceattr Vitality -1` already takes away one attribute level without refunding attribute points. Is this not what you mean?

**Comment by lordsrubka5** [comment]
If it works now then yes. Back when it was made negative numbers werent possible

**Comment by Sentropic** [comment]
Yeah it does now haha, maybe you can try it as well to be sure?
