### ISSUE TITLE
[Bug]: Prorpgitem attribute didnt loaded after doing relog ingame or doing /class reload

### ISSUE THREAD

**Issue by Jacatinelord** [promcteam/proskillapi#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

So, the items i made with the prorpgitems will not work (the attribute will not work or likely disappear) yet the text still on the item but have no effect. This only happened if i put the weapon i made with custom set with prorpgitem on the cast bar inventory (Slot 0-8 of cast bar), however the item will lose all of its prorpgitem attribute (like durability, class restriction, socket, and more) if only i run the command /class reload, or the player logged off and logging in again to the server. It just when i put the item ouside of the slot designed for skill, and i do /class reload or try to relog ingame, the item's attribute from prorpgitem like durability and damage doesnt count anymore. here's the video of what i mean. tried to seek any configuration but found nothing.

Video link on discord: https://cdn.discordapp.com/attachments/938499718823182337/972816871206297630/2022-05-08_18-57-59.mp4

Turns out after few helps from the community it was found that the item lost nbt tag,
This was before doing /class reload: https://cdn.discordapp.com/attachments/938499718823182337/972821628809539614/unknown.png
And this was after doing /class reload: https://cdn.discordapp.com/attachments/938499718823182337/972821629094735952/unknown.png

### Expected Behavior

Uhh i was hoping for the item still applying the nbt-tag from prorpgitem after doing the /class reload or even by relogging ingame.

It was hard enough to take item to the inventory, outside from cast bar.

### Steps To Reproduce

1. Give player a sword
2. Give attribute to the item with /qrpg set stats durability 1000 and /qrpg set damage 10 100
3. take the item to the part of cast bar area
4. try to attack mobs and see if the durability decreased
5. do /class reload
6. use the sword again to attack mob
7. and the durabilitty of qrpg doesnt decreased, instead it will decrease item's vanilla durability as the video
8. https://cdn.discordapp.com/attachments/938499718823182337/972816871206297630/2022-05-08_18-57-59.mp4

### Environment

```markdown
- Server Software: Paper Spigot 1.18.2
- ProSkillAPI Version: 1.1.7.16-1330244
- ProMCCore Version: 1.0.3.8-1150257
- Plugins: AdminUsefullCommand, AuctionHouse, Automessage*, BetterEnderChest, BKCommonLib, ChatItem, ChestCommands, Citizens, CMILib, CombatLogX, DecentHolograms, Denizen, DiscordSRV, DragonSlayer, DragonTimer, dtlTraders, DualWield, Duels, dynmap, EpicGuard*, Essentials, EssentialsChat, ExecutableItems, FarmLimiter, Geyser-Spigot, Jobs, Land, LevelledMobs, LuckPerms, MOTD, Mounts, Multiverse-Core, My_Worlds, nLogin, OnePlayerSleep*, OpenAudioMc, Parkour, Parties, PetDragon, PlayerParticles, ProMCCore, ProRPGItems, ProSkillAPI, ProtocolLib, Quests, QuickShop, RestartCountdown, RiseCore, SCore, Sentinel, ServerSigns, Shopkeepers, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, TabTPS, TradeSystem, UltimateChairs, UltraCosmetics, Vault, Votifier, VotingPlugin, WildStacker, WorldEdit, WorldGuard, XVaults
```

### Anything else?

Video link on discord: https://cdn.discordapp.com/attachments/938499718823182337/972816871206297630/2022-05-08_18-57-59.mp4

This was before doing /class reload: https://cdn.discordapp.com/attachments/938499718823182337/972821628809539614/unknown.png
And this was after doing /class reload: https://cdn.discordapp.com/attachments/938499718823182337/972821629094735952/unknown.png

**Comment by Travja** [comment]
If you're still around, could you try out the latest dev builds of ProSkillAPI and ProMCCore? @Jacatinelord

**Comment by Jacatinelord** [comment]
Hello, i am still here! And as always still using your plugins because its easy to use and also got an editor site.

Anyway, the lastest version is the newest post on discord?

**Comment by Travja** [comment]
Yes! You'll probably need the latest builds from each of the respective dev build channels on Discord

**Comment by Jacatinelord** [comment]
Hi im back, so i tried to install a fresh server with using same version of Paper and lastest ProSkillApi, ProMCcore, ProRPGitem on discord.
It still occurs, as i've make an item from /qrpg and using it still normal, then after using /class reload the NBT data from the item is gone, and the item's attribute back to vanilla minecraft.

**Comment by Jacatinelord** [comment]
Ah yes one thing, this bug occurs when you enabled the thing when you can switch between Cast Bar and Inventory bar, you know what i mean? the book on the edge of the bar.

As for now, i disabled its feature and changing my skills to using combos and bind.

**Comment by Travja** [comment]
Cool! Thanks for confirming that. I'll take a look over the next few days and see what I can find. I have an idea.

**Comment by lordsrubka5** [comment]
Yes, someone else had the same issue on discord. Long story short when swapping between cast bar and normal hotbar the plugin doesnt save your nbt tags and just saves the lore.

**Comment by Travja** [comment]
So for sake of simplicity and not re-inventing the wheel, I'm going to move how this is done to rely on ProMCCore's already established functions. I'm going to attempt to prevent any currently saved items from being deleted, but at present, I can't make any promises.
