### ISSUE TITLE
[Bug] Damage Lore Bug

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#30]
Several people have mentioned that the Damage Lore mechanic does not work. 

This is a mechanic in the editor: https://i.imgur.com/sdc0w9l.png

This is what the damage lore looks like in the editor: https://i.imgur.com/nfqMUO7.png

**Comment by Travja** [comment]
Potentially works. Damage Lore just requires some form of target.

**Comment by goflishMC** [comment]
fixed in latest dev build.

**Comment by h316098438** [comment]
Has this problem been solved in Proskillapi Alpha 1.17.1.01? It needs to be updated
