### ISSUE TITLE
[Enhancement] Eating Trigger

### ISSUE THREAD

**Issue by Canis8Lupus** [promcteam/proskillapi#301]
It's a suggestion of adding a trigger. 
This trigger, triggers whenever a player consumes or eats an item/something.

For example: Whenever the player eats cooked beef give hunger effect. 
Trigger: Eat/Consume; Target: Self; Condition: Item(cooked beef); Mechanic: Potion(Hunger).

This would be great for editing what happens when a player consumes or eats an item.

Hope is useful.
Thanks.

**Comment by Travja** [comment]
Duplicates #127. Though both will be considered when this is to be implemented.
