### ISSUE TITLE
[Bug]: Skill placeholder works not as expected

### ISSUE THREAD

**Issue by TheRealFrogman** [promcteam/proskillapi#302]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [x] I have tested without OP

### Current Behavior

There's a lore placeholder {req:skill} but it's always displayed as met

### Expected Behavior

I think this placeholder was supposed to show if the required skill was learned

### Environment

```markdown
- Server Software: Paper 1.17.1
- ProSkillAPI Version: 1.1.7.16-1330244
- ProMCCore Version: 1.0.3.8-1150257
```

### Anything else?

![pic](https://user-images.githubusercontent.com/74905689/168346345-e9e42a0d-ba08-4fb1-b137-a09a0e43c306.png)

**Comment by k437u** [comment]
I found out what this placeholder does
If incompatible skill is learned then it's not met

I wonder if there's a placeholder for skill requirement and would be grateful if you provided all the possible skill lore placeholders there is. Thanks

**Comment by k437u** [comment]
What i also found
{req:spent} returns not met when the amount of points spent doesn't match the specified requirement

**Comment by Travja** [comment]
I guess this is unclear, what needs to be adjusted here?

**Comment by k437u** [comment]
{Req:skill} doesn't show met or not met if the required skill is learned or not. It works exactly like {req:branch}. And all if these local skill lore placeholders aren't obvious, I think they should be provided in wiki or in the default config in the dynamic editor

**Comment by lordsrubka5** [comment]
From the images it looks like it doesn't exist at all so this might be more of a feature request than a bug report

**Comment by k437u** [comment]
It does, both {req:skill} and {req:branch} exist. They behave the same but idr what they do exactly. 

As far as I can remember, they both show incompatible skills. There's an option to set an incompatible skill which is shown by these.

**Comment by k437u** [comment]
Sorry if still unclear, I can't really test it right now so I'm going with what I can remember that's all

**Comment by Travja** [comment]
So currently, the placeholders `{req:branch}` and `{req:skill}` both indeed do the same thing. They check if the player has unlocked any incompatible skills or not. Would the 'value' side of this be better as a list of offending skills, or merely a list of all of the incompatible skills?

**Comment by k437u** [comment]
I don't get it...

**Comment by Travja** [comment]
Going to close this until further information is produced.
