### ISSUE TITLE
[Bug]: F clicks don't work

### ISSUE THREAD

**Issue by k437u** [promcteam/proskillapi#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

unable to use /class skill if skill combo contains F click

### Expected Behavior

you should be able to use  /class skill to level them up

### Environment

```markdown
- Server Software: Paper 1.17.1
- ProSkillAPI Version: 1.1.7.16-1330244
- ProMCCore Version: 1.0.3.8-1150257
```

### Anything else?

this issue was provided in this thread: https://github.com/promcteam/proskillapi/issues/82
and said to be fixed but it's not

the error being threw in the console is the same
here's mine https://pastebin.com/AgstDPLY

i also tried the dev build mentioned in the thread also didn't work

**Comment by Travja** [comment]
It appears that we haven't set the F setting as a default in the language.yml file. Could you add something in there along the lines of the following and report back if you still have issues?

```yaml
Combo:
    F: "&6Swap"
    ...
```

**Comment by k437u** [comment]
this didn't help
the error thrown in the console is 100% the same

**Comment by k437u** [comment]
and the ' char is used in this file instead of "
so i tried this as well and it didn't work too

**Comment by Travja** [comment]
If you can send your file so I can double check things, I'll do some debugging to track this down later.

**Comment by k437u** [comment]
the language.yml file?

**Comment by k437u** [comment]
i can't upload it here. can i send it to you in discord?

**Comment by k437u** [comment]
https://pastebin.com/rmZHfe3u here

**Comment by k437u** [comment]
i found out what happens...
on /class reload the string f: "&6Swap" just dissapears..
besides, any other string removed is restored upon reload

server restart does the same
