### ISSUE TITLE
[Bug]: health issue when using MMoitems and porskill at the same time

### ISSUE THREAD

**Issue by XiaoYu5530** [promcteam/proskillapi#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When I used MMoitems and proskillapi at the same time, the server did not report an error, but also without the OP, the equipment with health was switched, and the health returned to the original position, but Maxhealth was still in the original position.

### Expected Behavior

Hope to resolve health conflict between Proskillapi and MMoitems health

### Steps To Reproduce

no

### Environment

```markdown
- Server Software: spigot.1.16.5
- ProSkillAPI Version: 1.1.7.16-1330
- ProMCCore Version: no
- Plugins:
Plugins (66): RPGHealthIndicator, MmBossScore, Disposal, PlaceholderAPI, MySpawn, FarmProtect, PetBlocks, NBTAPI, AreaShow, ItemBox, MessageMe, MessageAnnouncer, EasyBackup, ProtocolLib, LibsDisguises, Mimic, LiteSignIn, PermissionsEx, ChatItemDisplay, HoloDrops, Vault, GPS, RPGHorses, HolographicDisplays, PlayerPoints, Dantiao, SignColors, BossShopPro, LotteryItem, WorldEdit, PlayerKits, Essentials, Multiverse-Core, TrMenu, CrazyAuctions, EssentialsChat, RPGMarketPlace, CrazyCrates, WorldGuard, MythicMobs, Multiverse-Inventories, UltraBar, EpicCraftingsPlus, BigDoors, EssentialsSpawn, SimplePortals, TitleManager, Guilds, Minerals, MoneyFromMobs, Citizens, Interactions, dtlTradersPlus, MythicLib, ProMCCore, DungeonsXL, HoloMobHealth, MythicArtifacts, CMILib, ProSkillAPI, MMOItems, BeautyQuests, TradeMe, PlayerTitle, RPGInventory, ProSkillAPIParties
```

**Comment by XiaoYu5530** [comment]
When my health is (30/30), it changes to (25/30) when I roll to switch slots, my class health is initially 25, gear is 30, and picking things up is the same.

**Comment by Travja** [comment]
What are you doing when it changes health value exactly?

**Comment by YYYYYYase** [comment]
> When my health is (30/30), it changes to (25/30) when I roll to switch slots, my class health is initially 25, gear is 30, and picking things up is the same.

You can try modifying config.yml    I solved the problem this way, at least you can try

Classes: 

  # Whether to use SkillAPI's health system
  modify-health: 'false'

  # The default health for players without a class
  classless-hp: '90000000'

**Comment by Travja** [comment]
I'm just going to go ahead and close this issue for a couple reasons. This issue is a bit stale and, in my opinion, not super critical. The health systems between MMOItems and ProSkillAPI are not designed to work very well together. Additionally, there isn't really a way to verify where additional health is coming from. SkillAPI very forcefully takes control of a player's health when using SkillAPI's health system. There could be work done to make it play a little nicer with other plugins, but the road to get there may not be the easiest.
