### ISSUE TITLE
[Bug]: Skills Stop Being Castable For Some Players

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Sometimes, some skills stop working but its only for some people. After a while a single player can no longer cast one skill while others on that class can cast it just fine. Relogging and swapping class doesn't fix it however reloading the plugin does fix it

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by lordsrubka5** [comment]
Update, happens most often on reloading the plugin where some skills are not applied correctly to the player. Sometimes they cant cast a skill if its castable or if its a left click/physical damage trigger it just ignores the skill at all. After a player relogs it updates and fixes it. The previous "after a while" might also happen on server restart and a player joins later? No idea its been a while since the "relogging doesnt fix it" issue and it has not happened since then

**Comment by Travja** [comment]
My suspicion is that if we address #315, this might also resolve itself, at least in part.

**Comment by Travja** [comment]
This and #315 are likely very related. Could be a conflicting plugin. My minimal setup doesn't seem to ever run into issues, even with 500 skills set up. According to stack traces provided, it could be related to the TAB plugin utilizing SkillAPI placeholders in the tab list.

**Comment by lordsrubka5** [comment]
I will try to keep TAB in mind, though it may even be reloading a bunch of times in a short period or even reloading while some skills are mid cast aka if they have repeat and they are active? At least that is the only thing that comes to my mind

**Comment by Travja** [comment]
Have you had any other issues with players not able to cast skills like this since adjusting for TAB?

**Comment by lordsrubka5** [comment]
Well yes and no, the plugin breaking itself is gone when tab doesnt try to pull placeholders from it mid reloading but the issue is somewhat there. Most often the left click and/or physical damage trigger breaks, cast doesnt break that often but i cant remember if it still happens or not. Sometimes happens after reload sometimes after swapping classes sometimes on login. 

Basically I have a skill that cancels physical damage and is auto unlocked so everyone must have it on selecting a class but sometimes it breaks and they can do physical damage. It fixes itself on relogging though

**Comment by Travja** [comment]
I'm going to go ahead and close this as it seems mostly resolved. If it persists in a greater capacity, we can reopen or create a new ticket.
