### ISSUE TITLE
[Bug]: MythicMobs use 5.0.2

### ISSUE THREAD

**Issue by FxRayHughes** [promcteam/proskillapi#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

use mythicmobs 5.0.2

### Expected Behavior

no report errors

### Steps To Reproduce

1. addplugin
2. start

### Environment

```markdown
- Server Software:
- ProSkillAPI Version: Paper version git-Paper-386 (MC: 1.18.2)
- ProMCCore Version: 1.1.7.13-ALPHA
- Plugins: 
Artifex, MythicMobs, PlaceholderAPI, ProMCCore, ProSkillAPI
```

### latest.log

https://pastebin.com/ch63uSKa

**Comment by lordsrubka5** [comment]
- Server Software:
- ProSkillAPI Version: Paper version git-Paper-386 (MC: 1.18.2)
- ProMCCore Version: 1.1.7.13-ALPHA

you typed server software into proskillapi version and proskillapi version into promccore version

regardless of that you are 4 versions behind. Update your proskillapi and promccore

**Comment by Travja** [comment]
MythicMobs v5 support has been added in later dev builds than what you're using. You can find them on the Discord.
