### ISSUE TITLE
[Enhancement]Add placeholder

### ISSUE THREAD

**Issue by Hoshino2001** [promcteam/proskillapi#33]
1. Player Current's Left skills name
2. Player Current's Shift+Left skills name
3. Player Current's Shift+Right skills name

%sapi_player_left:skillname%
%sapi_player_sleft:skillname%
%sapi_player_sright:skillname%

I might want to show it in the player profile

**Comment by goflishMC** [comment]
This would be low priority if we ever add it.

You could easily just use the placeholder and the correct skill, and do something like this: 
<pre>"Shift+Left: %papi_placeholder_here_skillname%"</pre>

You can get the list of placeholders here: https://promcteam.com/wiki/index.php?title=Proskillapi:Placeholders

**Comment by Hoshino2001** [comment]
> This would be low priority if we ever add it.
> 
> You could easily just use the placeholder and the correct skill, and do something like this:
> 
> "Shift+Left: %papi_placeholder_here_skillname%"
> You can get the list of placeholders here: https://promcteam.com/wiki/index.php?title=Proskillapi:Placeholders

uhmm i dont really get that..
