### ISSUE TITLE
[Bug]: shift+F=Copy items

### ISSUE THREAD

**Issue by YYYYYYase** [promcteam/proskillapi#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

After opening /class bar, press Shift+F to copy a skill icon

### Expected Behavior

Fix it

### Environment

```markdown
- Server Software: paper-1.16.5-794
- ProSkillAPI Version: proskillapi-1.1.7.16-1330244
- ProMCCore Version: promccore-1.0.3.8-1150257
- Plugins:
```

**Comment by Travja** [comment]
I actually can't even reproduce this. It's also worth noting that you're on a much older build than is current. I'll close this for now.
