### ISSUE TITLE
[Enhancement] Include Physical Damage Setting In Left Click Trigger

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#332]
**Describe the solution you'd like**

Left click trigger does not work when you look at a mob and try to hit it.
It would be nice to get a setting where this will be included.

This is a big help when there are skills that cancel physical damage because due
to how the plugin works, if one skill has cancel physical damage, all other left click
triggers will not happen when looking at a mob that is close enough to be physically hit

**Comment by Travja** [comment]
I just did this the other day. There is a new setting in the config. `Interaction.animation-is-left-click`. Basically, it makes it so any time your arm swings, it counts it as a left click. This could come with some caveats, but would allow left-clicking on entities to also trigger left click effects. Physical Damage as a means of triggering left clicks is a little weird and I found it less stable than the animation event. Animation is just disabled by default so as to only open potentially weird behavior to those that opt in.
