### ISSUE TITLE
Allow change text / disable text with /class exp command

### ISSUE THREAD

**Issue by SskyWorms** [promcteam/proskillapi#34]
Hello,
I have created a custom item that runs the psapi command when the player interacts with it and I want to change/hide the display of the message when the player gain xp with the command /class exp but can't find a way, I hope that could be add soon

**Comment by goflishMC** [comment]
> Hello,
> I have created a custom item that runs the psapi command when the player interacts with it and I want to change/hide the display of the message when the player gain xp with the command /class exp but can't find a way, I hope that could be add soon

did you look in language.yml?

**Comment by SskyWorms** [comment]
> > Hello,
> > I have created a custom item that runs the psapi command when the player interacts with it and I want to change/hide the display of the message when the player gain xp with the command /class exp but can't find a way, I hope that could be add soon
> 
> did you look in language.yml?

I mean this part
```java
            if (showMessage) {
                if (target != sender) {
                    cmd.sendMessage(
                            sender,
                            GAVE_EXP,
                            ChatColor.DARK_GREEN + "You have given " + ChatColor.GOLD + "{player} {exp} experience",
                            Filter.PLAYER.setReplacement(target.getName()),
                            RPGFilter.EXP.setReplacement("" + amount));
                }
                if (target.isOnline()) {
                    cmd.sendMessage(
                            target.getPlayer(),
                            RECEIVED_EXP,
                            ChatColor.DARK_GREEN + "You have received " + ChatColor.GOLD + "{exp} experience " + ChatColor.DARK_GREEN + "from " + ChatColor.GOLD + "{player}",
                            Filter.PLAYER.setReplacement(sender.getName()),
                            RPGFilter.EXP.setReplacement("" + amount));
                }
            }
        }
```

**Comment by SskyWorms** [comment]
Also allow to hide it too

**Comment by Travja** [comment]
This actually has been a thing for a long time... All that is needed is that the last argument of the command be set as `false` and it won't send the messages.
