### ISSUE TITLE
[Enhancement] Stopsound

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#341]
**Describe the solution you'd like**

There is a mechanic called sound which does /playsound but I dont see /stopsound

**Comment by lordsrubka5** [comment]
Also a way to play the sound to a single person instead of the whole area would be nice

**Comment by YYYYYYase** [comment]
> **Describe the solution you'd like**
> 
> There is a mechanic called sound which does /playsound but I dont see /stopsound

You can directly select the people you want to stop and execute the command/stopSound for them

**Comment by YYYYYYase** [comment]
> Also a way to play the sound to a single person instead of the whole area would be nice

The same is true for this problem, simply select a single target and have them execute the command /playsound

**Comment by lordsrubka5** [comment]
Closing this since sound mechanic is played for area and stopsound is for one person
