### ISSUE TITLE
[Bug]: F Key Item Attribute Update

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Equipping offhand item with F key will a lot of the times not properly
apply an update to the attributes a player has. What exactly does this break?

1. Holding a weapon then clicking F and then swapping to another weapon to
dual wield will only apply attributes from the main hand item

2. Dragging a weapon to offhand slot to apply its stats and then pressing F will
keep the stats applied and then you can equip any two handed item and you have
a two handed item stats while also having that previous item stats applied on top of
that making you very much brokenly op

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
Resolved
