### ISSUE TITLE
[Bug]: Stat Mechanics does not work correctly

### ISSUE THREAD

**Issue by YYYYYYase** [promcteam/proskillapi#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

[skill.3.zip](https://github.com/promcteam/proskillapi/files/9175535/skill.3.zip)

This Skill does not cause the player to move at zero speed

### Expected Behavior

Get this Mechanic working right

### Steps To Reproduce

Use it

### Environment

```markdown
- Server Software:paper-1.16.5-794.jar
- ProSkillAPI Version:proskillapi-1.1.7.16-1330244.jar
- ProMCCore Version:promccore-1.0.3.8-1150257.jar
```

**Comment by lordsrubka5** [comment]
did you try with 0.001? Also there is another mechanic called status which you can use root but that forbids them from looking around as well

**Comment by YYYYYYase** [comment]
> did you try with 0.001? Also there is another mechanic called status which you can use root but that forbids them from looking around as well

I just tried that. It didn't work either.I also tried other options, like Health, that didn't work either
I ended up giving the player -100 level speed to fix it, but anyway, it's a bug

**Comment by lordsrubka5** [comment]
Well yeah not sure how the plugin performs with zeros with actual values since it also doesnt register enemies in area targetter that are exactly 0 blocks away from the center but any value above 0 should work fine

**Comment by Travja** [comment]
I actually just tested this skill. Just dropped it into my server and it worked fine. Granted, I'm on 1.19, so I'm not sure if that makes any difference. Will test with 1.16.5 and update you shortly.
