### ISSUE TITLE
[Bug]: Citizen Sentinel Enemies dont take damage

### ISSUE THREAD

**Issue by Svastojed** [promcteam/proskillapi#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Any Sentinel doesnt take damage even if it attacks you.

### Expected Behavior

Have Sentinels take spell/skill damage

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Travja** [comment]
This has been reported as an enhancement, #117. Though no resolution has been made as of yet. It appears that some people are able to damage Sentinels with skills without issue. What kind of skills are you using?

**Comment by Svastojed** [comment]
area of effect single damage target damage on hit nothing works vs them only meele damage with weapons

**Comment by Travja** [comment]
Are you in any specific non-pvp zones or anything?

**Comment by Svastojed** [comment]
no i tested this with specific pvp worlds(entire world enabled), with pvp regions. in generell it doesnt work.

**Comment by Travja** [comment]
Hmm. This is just an interesting one to try to tackle. I don't use Sentinels, nor am I aware of how to use it. But to debug and figure out what's going on, I'd have to set some things up and run through some tests.

Are you sure that the targeting itself is working?

**Comment by Svastojed** [comment]
Yes i have 2 mc accounts for testing and my alt got hit by every effect. so targeting for the skill itself(outside sentinel) seems to work.

**Comment by Travja** [comment]
> targeting for the skill itself(outside sentinel) seems to work.

What do you mean by this? Could you set up a skill that launches targets in the air and make sure the Sentinel is being targeted?

**Comment by Svastojed** [comment]
i can test it on weekend, half my colleges called in sick so i got 5x 16 hour shifts this week.

**Comment by Travja** [comment]
@Svastojed I'm just wondering if you have any more information on this?
