### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BeanOat** [promcteam/proskillapi#35]
**Describe the bug**
Skills not loading into /class skill. Tried resetting my config and dynamics folder, nothing fixes it tho. Absolutely no errors in log either, latest 1.1.5 version.

**To Reproduce**
SkillAPI 1.1.5, Spigot 1.16.5 server, and just try to load make a class with a skill, and the skill doesn't load. Sometimes it'll load one, and only one skill, but upon removing that one and trying to load another as a test, the other skill won't even show.

**Expected behavior**
Should just not load the skills. 0 errors in config.

**Versions (please complete the following information):**
-  Spigot Version: 1.16.5
 - Plugin Version: 1.1.5

**Additional info**
Not sure if it worked on previous versions honestly, I never even used the command, just had the skills auto level so they would auto show on your skill bar in your hotbar 0-8, but now I am doing Borderlands Style skill trees and noticed it just isn't working.

**Comment by mkcoldwolf** [comment]
Did u enable the skill with `/class customize` ?
If u update skill/skill, they might be default goes hiding from the `/class skill` gui
Switch to the correct skill for class menu in `/class customize` and drag the skill into the gui 
This problem frustrated me too when i get to use skillAPI bcs of no error/warnings

**Comment by BeanOat** [comment]
Oh shit it worked, thank you so much man, this is actually awesome, I can
customize the skill tree however I want it to look, let's go! This is even
better than what I imagined, I'm currently making an MMORPG with
Borderlands inspiration, and I wanted to incorpate some borderlands style
skill trees using skill augments, etc, and it just wasn't working, but now
I can, awesome!! You guys are the best.
