### ISSUE TITLE
[Bug]: Targetters can target Spectators

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment]
I assume this refers to players in Spectator mode and not just invisible players. For sake of plugins/skills I think invisible players should still be targeted. Does it also target players on Creative mode?

**Comment by lordsrubka5** [comment]
Yes I mean spectator gamemode and ot does also target creative people. Which I guess should also be removed I see no point where you would need a skill to work on you in creative unless its a self target which should work regardless of gamemode.
