### ISSUE TITLE
[Enhancement] Division

### ISSUE THREAD

**Issue by RacerN2O** [promcteam/proskillapi#359]
**Is your feature request related to a problem? Please describe.**
Currently, you can multiply, add and subtract in the skill editor. Divisions are not possible so a lot of math is unavailable, which can create frustrating situations.
For example, I've been trying to make a system that takes an attack speed value and turns it into a number to use for cooldowns. It is simply not possible as I would have to divide 1 by the value I have.

**Describe the solution you'd like**
A value divide mechanic that allows you to divide two values by eachother, a number by a value and a value by a number.

For example:
value/value
X/value
value/X

Would all be very useful, where X does not have to be a preexisting value and is a fixed number.

**Describe alternatives you've considered**
I have worked around with placeholders and placeholder math but I have currently hit a road block trying to get info that doesn't have a placeholder for it, whereas SAPI could simply read item lores and such.

**Additional context**
That is all.

**Comment by RacerN2O** [comment]
In general it would be more useful to just have a "Value Math" function instead of the current system because skills can get bloated, but I'd be happy with just being able to do all the math that I need in the first place.

**Comment by RacerN2O** [comment]
Accidentally closed, whoops

**Comment by lordsrubka5** [comment]
copy of https://github.com/promcteam/proskillapi/issues/311
additionally this too https://github.com/promcteam/proskillapi/issues/175
