### ISSUE TITLE
[Enhancement] Add Shield Trigger

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#362]
**Describe the solution you'd like**

A trigger for a successful shield block

**Comment by goflishMC** [comment]
Options: 
<pre>
Mana: true/false
Cooldown: true/false
#If shield raised is selected this will trigger when they raise their shield
#If shield block is selected this will trigger when they successfully block with their shield
Type: Shield Raised/Shield Block
</pre>

**Comment by fructozer** [comment]
1. shield raised can check with right click and item condition. So just detect when they successfully block with their shield
2. I cant find any event called when player block dmg with shield. So i use <PlayerStatisticIncrementEvent>
3. <PlayerStatisticIncrementEvent> can check how many damage was blocked. So i will add max and min dmg req to trigger
