### ISSUE TITLE
[Bug]: Player is not treated as an ally to wolf summons

### ISSUE THREAD

**Issue by JakeBat-H** [promcteam/proskillapi#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Wolves that are summoned off of Skills do not treat the player currently as an ally. 

For example:

Our ability summons 2 wolves, one provides a healing aura to allies, one provides damage boost to allies. We would like these to be AOE effects, not only for the dogs, but also for the player, and his allies in parties. Currently, the dogs do not even affect the player. 

### Expected Behavior

I expected the wolves to treat players/players in parties as allies for the purposes of bonus effects and auras.

### Environment

```markdown
- Server Software: Magma
- ProSkillAPI Version: 1.1.7.17-3441532
- ProMCCore Version: promccore-1.0.3.9-3421730
- Plugins:
LuckPerms, PlaceholderAPI, Vault, WorldEdit, DeluxeTags, RiseCore, WorldGuard, BanItem, CMILib, ProMCCore, CMI, ProSkillAPI, ProSkillAPIParties
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

I'm sorry if this is supposed to be in enhancement rather than bugs, I assumed that this would be an unintended interaction.

**Comment by JakeBat-H** [comment]
While I still think this would be a nice feature that is intuitive, we worked around it by assigning the caster with the auras while the dogs are alive, though we'd still prefer that the dogs themselves give the auras, this is the workaround we did, which works well!

**Comment by joosii** [comment]
bump
