### ISSUE TITLE
[Enhancement] Particle Line

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#369]
**Describe the solution you'd like**

A way where we can draw straight lines
This should support all 3 axis or an option to choose if it should be flat or 3d
2 scenarios:

**Targetted**
It has options for start and end, if start is not stated it will assume its caster (or armorstand or dog if its under those). If end is not stated it will assume its the target. Both fields support remember mechanic in case you somehow want to change from what it draws

**Not targetted**
The particle starts from caster and you define where its pointed. Option for relative to caster (direction of looking) or to north, options for length of the line

Both of those have options for offset, option for total amount of particles, options for radius of aragement (particle spread), options for angle offsets (up and side)

**Comment by Sentropic** [comment]
Maybe a raycast mechanic is what we really need, executing children components along the line. Achieves as much as the skill i showed, but simpler.

Also here's the skill in case you wanna see it in the editor:
```Raytrace:
  name: 'Raytrace'
  prefix: '&6Class 1'
  group: 'class'
  mana: '&2Mana'
  max-level: 40
  parent: ''
  needs-permission: 'False'
  exp-source: 273
  mana-regen: 1
  tree: 'Requirement'
  skills:
  - 'Test'
  icon: 'Jack o lantern'
  icon-data: 0
  icon-lore:
  - '&dClass 1'
  blacklist:
  - ''
  action-bar: ''
  attributes:
    health-base: 20
    health-scale: 0
    mana-base: 20
    mana-scale: 0
    vitality-base: 0
    vitality-scale: 0
    spirit-base: 0
    spirit-scale: 0
    intelligence-base: 0
    intelligence-scale: 0
    dexterity-base: 0
    dexterity-scale: 0
    strength-base: 0
    strength-scale: 0
```
