### ISSUE TITLE
[Bug]: cause damage to caster

### ISSUE THREAD

**Issue by longdt1425** [promcteam/proskillapi#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

when I use a skill to damage myself it doesn't work as I expected, it doesn't deal any damage but the other mechanics still work on me.
![Capture](https://user-images.githubusercontent.com/53807048/186657087-328c7320-3054-4513-9355-4c8a88a93f3c.PNG)
![Capture](https://user-images.githubusercontent.com/53807048/186657309-3f22b254-b13d-47ea-8e51-b22de2463900.PNG)

### Expected Behavior

I want it to hurt me.

### Steps To Reproduce

1. cast skill by command, skill bar, combo.
2. Action doesn't happen as expected

### Environment

```markdown
- Server Software: Spigot 1.16.5 Java11
- ProSkillAPI Version: 1.1.7.17
- ProMCCore Version: promccore-1.0.3.9-3421730
- Plugins:LuckPerms, Hibernate, PlaceholderAPI, Vault, FMCSAssistant, ProtocolLib, Denizen, MythicMobs, Essentials, EssentialsChat, ProMCCore, EssentialsSpawn, MythicMobsExtension, ProRPGItems, ProSkillAPI, ProSkillAPIParties.
```

### latest.log

[latest.log](https://github.com/promcteam/proskillapi/files/9424439/latest.log)

### Anything else?

nope

**Comment by Sentropic** [comment]
Solved by https://github.com/promcteam/proskillapi/commit/67793be202b9eaab3439da48fb70b8c2286ba84d
