### ISSUE TITLE
[Bug]: The AOE sword swing (sweeping edge, but not the enchantment) scales absurdly hard/incorrectly with strength 

### ISSUE THREAD

**Issue by JakeBat-H** [promcteam/proskillapi#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Currently, on our server, when a sword attacks, the actual attack deals normal damage, but the AOE damage applied by the sword "slash" effect scales insanely hard with strength for some reason. A normal attack could be hitting for 50, but the aoe effect could be hitting everything around it for like 300. 

### Expected Behavior

I expected the aoe slash to be doing less damage than the actual hit as it does in vanilla. 

### Steps To Reproduce

1. Get a sword
2. Level strength
3. Swing in a batch of mobs 

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
LuckPerms, PlaceholderAPI, Vault, WorldEdit, DeluxeTags, RiseCore, WorldGuard, BanItem, CMILib, ProMCCore, CMI, ProSkillAPI, ProSkillAPIParties
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment]
So disabling ProRPGItems, I'm actually not seeing anything out of the ordinary with this. With ProRPGItems enabled, I'm actually not seeing the slash effect do any damage to mobs apart from the actually targetted mob. I'm going to go ahead and close this for the time being as there is potentially a different issue at play altogether.

**Comment by JakeBat-H** [comment]
No we didn't

**Comment by Travja** [comment]
Cool yeah if you just want to see if that's still an issue or not, that would be good.
