### ISSUE TITLE
[Bug]: Ally Targeting Mobs

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Iron golems from mythicmobs are sometimes treated as ally even with the setting in config for mob allies set to false and even if the mob is clearly the enemy by being damageable and aggroing the player

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by lordsrubka5** [comment]
note that it is also treated as enemy at the same time since damage skills can attack it

**Comment by Travja** [comment]
So this is interesting to me... Iron golems should never be considered an ally based on the passive ally setting as iron golems aren't considered 'passive' (or Animals, they're actually just Golems, which are Creatures). The only reason they might be considered allied is if something (MythicMobs or some other plugin--even WorldGuard) stops them from being damaged in the ally check. What kinds of things are you finding treat it as an ally most consistently?

**Comment by Travja** [comment]
Closing this as this is kind of stale and needs more information before we can really tackle this. Feel free to re-open with more information.
