### ISSUE TITLE
Player data lost caused by threads

### ISSUE THREAD

**Issue by MrMks** [promcteam/proskillapi#375]
Write at the beginning, I didn't test if it will happens with proskillapi. 

It is a bug exist in original skillapi, I checked the newest code of proskillapi on GitHub, and it is same to the original one, so I believe that this bug will happens with proskillapi, too.

This happens when threads trying to read or/and write to the same file at the same time. As far as I can see, there are two threads may access the same file at same time, one from SaveTask, and one from async-scheduler when the player logs out. If this happens, the file will contains wrong contents, and failed to be read when the player try to login next time.

**Comment by Travja** [comment]
Huh. We've seen this bug a few times but couldn't really figure out why this was happening, especially because I was never able to reproduce it myself. If it's problems with read/write overlapping, we should be able to combat that.
