### ISSUE TITLE
[Enhancement] New Mechanic:  Damage Type

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#377]
Similar to damage mechanic, but lets you set the damage types from "spigot damage causes" using a drop down list

Spigot Damage Cause: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

**Comment by lordsrubka5** [comment]
or instead of new mechanic just putting that inside the existing damage mechanic

**Comment by Sentropic** [comment]
Changing the damage cause used by the plugin isn't possible directly, but maybe it's possible to "simulate" a different damage cause. For that I need to know though, what's the purpose of changing the damage cause?

**Comment by lordsrubka5** [comment]
Prorpgitems elements group specific damage causes under the elemental defense. You can technically do a workaround on this by making a skillapi atrribute under the same name of the defense and set it to reduce specific damage classifier

**Comment by Sentropic** [comment]
This was done using a hacky solution, but works up to Java 17. Might have to keep an eye out for incopatibilities with certain Java versions, in which case the exception will be printed in console. But works for now :)
