### ISSUE TITLE
[Bug]paper-1.17.1-103  use/class forcecast %player% xxx  That is not a valid player name

### ISSUE THREAD

**Issue by kerorozsl** [promcteam/proskillapi#38]
[Bug]paper-1.17.1-103  use/class forcecast %player% xxx 
 Console display
 That is not a valid player name

**Comment by Travja** [comment]
This should be resolved as of [7fae3bf](https://github.com/promcteam/proskillapi/commit/7fae3bf35fb633cda92a5e96256ea313765113f5). This build has not been posted as of yet and I have not _actually_ confirmed that this works yet. Just giving you an update.

**Comment by goflishMC** [comment]
> This should be resolved as of [7fae3bf](https://github.com/promcteam/proskillapi/commit/7fae3bf35fb633cda92a5e96256ea313765113f5). This build has not been posted as of yet and I have not _actually_ confirmed that this works yet. Just giving you an update.

I just tested this. My skill: https://i.imgur.com/uf6McIK.png

I typed the command in the console (this is a console only command) and got this result: https://i.imgur.com/vs9bRqR.png

**Comment by goflishMC** [comment]
Fixed in latest dev build
