### ISSUE TITLE
[Enhancement] New Stats for attributes.yml

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#385]
damage-type-damageType
-adding points in this would increase the amount of damage you do with this type of damage
-https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

attribute-attributeType
-adding points in this would increase another attribute)

**Comment by lordsrubka5** [comment]
Uh first two are the same and they already exist.
Third one is useless?

**Comment by goflishMC** [comment]
First one is meant to be from spigot damage causes, and the 2nd was a duplicate, my bad.
