### ISSUE TITLE
[Enhancement] Experience Boosters with permissions

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#387]
New Permission
skillapi.exp.booster.<percentAmount>

Example:
skillapi.exp.booster.10

In the example above the player would get 10% more experience gains

**Comment by neYaANK** [comment]
Should the boosts stack from different permissions or should we take the highest boost?

**Comment by goflishMC** [comment]
> Should the boosts stack from different permissions or should we take the highest boost?

take the highest boost

**Comment by Travja** [comment]
We've kind of adjusted this a little further. In order to get a 10% boost, you'd have to use a permission of `xx.110`. This allows us to set a permission of `xx.50` to give the player only 50% of the original exp allowing for some nerfing and not just boosting.
