### ISSUE TITLE
[Bug] Using attributes to increase attack speed will bug when reload

### ISSUE THREAD

**Issue by luattruong29** [promcteam/proskillapi#39]
When we use attributes to increase player's attackspeed, it will be stacked infinitely in the weapon whenever we reload skillapi plugin.  You can try this (attack-speed: 'a*0.01+1*v') with any attribute and level up some points in it, then reload the plugin you can see that bug

**Comment by mkcoldwolf** [comment]
This is one of the bug caused by the old horrible attribute system
![image](https://user-images.githubusercontent.com/32544898/126363462-17fa72bd-3107-4822-94c1-76dd6d7d4da5.png)
Was just simply add the number up to the base value instead of calculating each time
The rework of mccwtech fork (implement of Attribute Modifier) should also cover this issue

**Comment by Travja** [comment]
@mkcoldwolf Would you be able to link some of the code from MCCWTech's fork that would resolve this issue?

**Comment by mkcoldwolf** [comment]
@Travja 
Sorry didn't have chance to push the update to the fork b4
Now its updated, in
https://github.com/mccwtech/proskillapi/commit/1d0105f5f02b63ad72017898db4c377efb7dfb1b#diff-6e8e511af28b9ec8c1d8865aa7af01d56d992f1d6946bfa41f83bc0d29cfd48bR1534
We now directly calculate the player's desired Minecraft attribute again by calling
PlayerData#updatePlayerStat()

Its kinda a big change, thats why i haven't decided to push it before its stable
Now its seems stable enough to me, but may still require some minor changes before i PR to here

**Comment by goflishMC** [comment]
> @Travja
> Sorry didn't have chance to push the update to the fork b4
> Now its updated, in
> [mccwtech@1d0105f#diff-6e8e511af28b9ec8c1d8865aa7af01d56d992f1d6946bfa41f83bc0d29cfd48bR1534](https://github.com/mccwtech/proskillapi/commit/1d0105f5f02b63ad72017898db4c377efb7dfb1b#diff-6e8e511af28b9ec8c1d8865aa7af01d56d992f1d6946bfa41f83bc0d29cfd48bR1534)
> We now directly calculate the player's desired Minecraft attribute again by calling
> PlayerData#updatePlayerStat()
> 
> Its kinda a big change, thats why i haven't decided to push it before its stable
> Now its seems stable enough to me, but may still require some minor changes before i PR to here

were you able to work this out so you can do a pull request?

**Comment by Travja** [comment]
Recent dev builds have the mccwtech forked pull request included and should resolve this issue.
