### ISSUE TITLE
[Bug]: target self and true damage

### ISSUE THREAD

**Issue by vtcmnb** [promcteam/proskillapi#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

I set mechanic damage to true under target self, it doesn't do anything

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment]
I was unable to reproduce this. True Damage worked as intended. If you're doing normal damage, it used to no work against oneself if you had knockback set to true, but this should be resolved also.
