### ISSUE TITLE
[Bug]: Buff Mechanic not working

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When I use the buff mechanic there is no change in damage/defense. Tried with multiplier and flat damage.

### Expected Behavior

The player getting buffed with defense should have damage reduced when being attacked.

The player getting buffed with damage should do more damage when attacking.

This is not happening in either case.

_No response_

### Environment

```markdown
- Server Software: Spigot 1.19.2
- ProSkillAPI Version: 1.1.7.17-3441532
- ProMCCore Version: 1.0.3.9-3421730
- Plugins: https://i.imgur.com/im4fHdc.png
```

**Comment by lordsrubka5** [comment]
I use skills with buff though? unless it broke on the latest version

**Comment by goflishMC** [comment]
> I use skills with buff though? unless it broke on the latest version

not sure, I just tested with latest version and it doesn't seem to work with the buff mechanic

**Comment by Travja** [comment]
This honestly should still be working fine unless the damage event is getting cancelled somehow. Then again, with ProRPGItems, things might be misbehaving. Have you tested without ProRPGItems?

**Comment by goflishMC** [comment]
> This honestly should still be working fine unless the damage event is getting cancelled somehow. Then again, with ProRPGItems, things might be misbehaving. Have you tested without ProRPGItems?

I'll test that
