### ISSUE TITLE
[Bug]: Quests Plugin Module On The ProSkillApi Quests Class Requirement is more than 1

### ISSUE THREAD

**Issue by crisnawidhi** [promcteam/proskillapi#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Hello, i've been facing this problem since first time i used ProSkillApi.
I read that the plugin support module on Quests Plugin by Pikamug, and somehow it bugged...

The bug i meant is that the Requirement is duplicated and somehow it did not complete the requirement even you are eligible for the requirement, lemme give example.

I set a Quest's requirement to Grouo Class Priest, with level 10. And i am as a player already a Priest Level 40, yet i cant get the quest because of this bug somehow. Check this image: The other two is black text and the last is green.
![image](https://user-images.githubusercontent.com/28751874/197538769-51d07837-fbe8-4086-88e1-26568f8a8dab.png)

Here also the menu when selecting SkillApiModule requirement, it is doubled somehow.
![image](https://user-images.githubusercontent.com/28751874/197538999-1907eeaf-ab4f-4750-8167-68f2add87633.png)

Here is the requirement i typed on Level Requirement
![image](https://user-images.githubusercontent.com/28751874/197539167-3374b4ed-26a9-41d6-b376-e2acbf9cb892.png)

I've asking this to the Quests Dev Team, and it said probably from the module creator not their plugin.

### Expected Behavior

Well, i was hoping that the Class Level Requirement only showed once. And it will not bugged i guess

### Environment

```markdown
- Server Software: Paper 1.18.2
- ProSkillAPI Version: 1.1.7.17-4252334
- ProMCCore Version: 1.0.3.9-3421730
- Quests Version: 4.5.2-b355

- Plugins: AFKPlus, AuctionHouse, Automessage*, BetterEnderChest, BKCommonLib, Boss, BungeeGuard, ChatItem, ChestCommands, Citizens, CMILib, CombatLogX, DamageIndicator, DecentHolograms, Denizen, DiscordSRV, DragonSlayer, DriveBackupV2, dtlTradersPlus, Duels, DungeonSystem, Essentials, EssentialsChat, ExecutableBlocks, ExecutableItems, Geyser-Spigot, GPS, GPS-Quests, HealthBar, Images, Interactions, InteractiveBoard, Jobs, Lands, LeadFix, LevelledMobs, LibsDisguises, LuckPerms, Maintenance, MCPets, MMOItems, ModelEngine, MOTD, Mounts, Multiverse-Core, My_Worlds, MythicLib, MythicMobs, OnePlayerSleep*, OpenAudioMc, Oraxen, Parties, PetDragon, PL-Hide, PlaceholderAPI, PlayerParticles, PlayerPoints, PowerCamera, ProMCCore, ProRPGItems, ProSkillAPI, ProtocolLib, pvparena, PvPManager, Quests, RealScoreboard, RestartCountdown, RiseCore, RPGChat, SCore, Sentinel, ServerSigns, ShopGUIPlus, Shopkeepers, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, StaffChat, StarMail, TAB, TradeSystem, UltimateChairs, UltimateStatistics, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WallJump, WorldEdit, WorldGuard, WorldGuardExtraFlags, XVaults
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

I checked the console it does nothing wrong, and it just loaded the module no error. Thankyou !

**Comment by Travja** [comment]
Can you share any applicable configuration files for Quests relating to this specific quest?
