### ISSUE TITLE
Can you add a hologram damage only for mechanic damage?

### ISSUE THREAD

**Issue by Watcharavit-Jiracheepputtana** [promcteam/proskillapi#4]
This feature is when you use Mechanic damage in skillapi it will show the damage from mechanic damage

**Comment by goflishMC** [comment]
> This feature is when you use Mechanic damage in skillapi it will show the damage from mechanic damage

are you talking about showing the damage visually each time you do damage?

**Comment by Travja** [comment]
Pending a more in depth description of this request, I am going to close this ticket as it has been months without a response.
