### ISSUE TITLE
[Enhancement] Autoload new skills into the GUI

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#404]
With this probably being the #1 most confusing issue, I'd like to autoload new skills into the GUI.

**Comment by lordsrubka5** [comment]
Config option to disable auto loading skills in the gui

**Comment by Sentropic** [comment]
Covered by https://github.com/promcteam/proskillapi/commit/3f7ea1463f89d8ada6f2b035d3a48e6a0a8052e7 and https://github.com/promcteam/proskillapi/commit/6159c0f848387c4e27b2202bdbc756b931e1cc43
