### ISSUE TITLE
[Enhancement] Missing EntityTypes

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/proskillapi#409]
Just noticed that some of the vanilla mobs need to be updated.

There is missing
Chicken Jockey
Drowned
Hoglin
Phantom
Piglin Brute
Pillager
Ravager
Shulker
Skeleton Horseman 
Spider Jockey
Warden
zombie villager
zoglin

**Comment by Travja** [comment]
Thank you! I'm not sure how those snuck by without being added. I know @Sentropic just created a new generator for all of that just recently. With the exception of jockeys/combination mobs, this should hopefully be as simple as us running the data generator again.

**Comment by Travja** [comment]
Actually, on closer inspection of the data that's in our frontend code, aside from jockeys, those should all be showing up. What target MC version are you using?

**Comment by DrHeretic** [comment]
Current, I just noticed it wasn't in the config

**Comment by Travja** [comment]
Which config are you referring to?

**Comment by DrHeretic** [comment]
Main config.

**Comment by DrHeretic** [comment]
![image](https://user-images.githubusercontent.com/88398845/201445213-e54837dc-e5c3-4f90-b607-ba3090c14505.png)
Ya from what is on the mob list of aggressive mobs via minecraft the ones I listed are missing

**Comment by Travja** [comment]
I would think you could add them yourself without issue, but will work on getting them loaded my default.

**Comment by goflishMC** [comment]
> I would think you could add them yourself without issue, but will work on getting them loaded my default.

Can I add  those here: https://github.com/promcteam/proskillapi/blob/development/src/main/resources/config.yml

or does that file get generated from somewhere else?
