### ISSUE TITLE
[Bug]True Damage when not set to True

### ISSUE THREAD

**Issue by RebelRanger** [promcteam/proskillapi#41]
When using the Damage mechanic it will deal true damage(damage ignores armor) when the "Apply Knockback" option is set to false. Setting the "Apply Knockback" to true will fix this but is obviously a bug.

**Comment by Travja** [comment]
This is specifically the code that I believe we're looking at for this issue. True damage should only be activated if the 'true' setting is set to true, regardless of knockback settings. Could you confirm that you don't have true damage enabled?
```java
            if (trueDmg) {
                skill.trueDamage(target, amount, caster);
            } else {
                skill.damage(target, amount, caster, classification, knockback);
            }
```

**Comment by goflishMC** [comment]
I tested this in the latest dev build 1.1.6.3 (not yet released) and this no longer seems to be an issue.
