### ISSUE TITLE
[Enhancement] Placeholder for Account

### ISSUE THREAD

**Issue by redadykai** [promcteam/proskillapi#412]
**Is your feature request related to a problem? Please describe.**
Placeholder for accounts

**Describe the solution you'd like**
Placeholder for accounts that will display 
level, class and group per account 

for ex. 
```
%sapi_<account_id>_level%
%sapi_<account_id>_maingroup%
%sapi_<account_id>_class%
```

**Comment by Travja** [comment]
Also see: #400
