### ISSUE TITLE
[Bug]: Items get removed from your hotbar when switching to cast mode

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

The items in your hotbar get removed when you switch to cast mode with the book. When you switch out of cast mode, your items return.

### Expected Behavior

When you switch to cast mode the item you are holding should get moved down the hotbar

This allows you to still use your weapon when casting

### Steps To Reproduce

1. Put items in your hotbar
2. Switch to cast mode
3. You'll see all your hotbar items disappear
4. When you switch out of cast mode your items get returned

### Environment

```markdown
- Server Software: 1.19.2
- ProSkillAPI Version: 1.1.7.18-20221115.074205-20
- ProMCCore Version: 1.0.3.10-20221110.064223-9
- Plugins: https://i.imgur.com/ohoUcMy.png
```

**Comment by Travja** [comment]
This isn't always possible though

**Comment by goflishMC** [comment]
> This isn't always possible though

If they are using all the hotbar slots for skill slots, then you are right.

I only had 1 item in my hotbar. Most people still want to use their weapon and a couple potions.
