### ISSUE TITLE
[Bug]: Could not pass event AsyncPlayerPreLoginEvent to ProSkillAPI v1.1.7.18-SNAPSHOT

### ISSUE THREAD

**Issue by Daisidaisy** [promcteam/proskillapi#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

https://pastebin.com/EnKQcPXM
it happens when 1 player joins the server

### Environment

```markdown
- Server Software: paper 1.16.5
- ProSkillAPI Version: ProSkillAPI v1.1.7.18-SNAPSHOT
- ProMCCore Version: promccore-1.0.3.8-1150257
- Plugins:  Aliases*, BattlePass, BlockEffects, BossBarHealth, Citizens, ClearLag, CustomDrops, DeluxeCoinflip, DeluxeMenus, EconomyShopGUI, EliteLootbox, Essentials, EssentialsSpawn, EvenMoreFish, ExtraStorage, GiftCodes*, ItemJoin, KiteBoard, LiteBans, LuckPerms, MMOItems, MyPet, MythicLib, MythicMobs, Oregen3, PlaceholderAPI, PlayerData*, PlayerKits, PlayerPoints, PlayerVaults, PlugManX (PlugMan), ProMCCore, ProSkillAPI, ProSkillAPIParties, ProtocolLib, PuerkasChat*, SkinsRestorer, SuperiorSkyblock2, SupperSeason, TAB, TimeIsMoney*, Vault, ViaBackwards, ViaRewind, ViaVersion, Vouchers, WorldEdit, WorldGuard, XPBoost*
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment]
Is this just one player, or is this any player that joins?

**Comment by Daisidaisy** [comment]
> 

Many people too

**Comment by Travja** [comment]
It looks like your ProMCCore build is outdated. Could you try grabbing the newest builds of both ProSkillAPI and ProMCCore from our Discord and see if you have the same problem?

**Comment by Daisidaisy** [comment]
I have updated the version promccore-1.0.3.10-20221110.064223-9
it's still like that
but 
i deleted everything in the playerdata section it was gone, when i log out and rejoin the server it shows up again

**Comment by Travja** [comment]
Have you tried turning the server off, deleting the data, then starting it up again and see if the error is still there?

**Comment by Daisidaisy** [comment]
I just did that, the first time I joined the server it was normal but the second time it showed up

**Comment by Travja** [comment]
Can you try the new build that'll be posted to Discord in a few minutes and tell me if that fixes it?

**Comment by Daisidaisy** [comment]
sorry for the late reply, seems to be no longer the problem
