### ISSUE TITLE
categories for the dynamic Editor 

### ISSUE THREAD

**Issue by Tainted-Valor** [promcteam/proskillapi#420]
I would really like if there is a way to add skills to categories just like a skill that would look like a skill but the text is bold and you can just drag and drop other skills under it so you know what they are I'm having a really difficult time managing all of the skills and keeping them in line and track of what I'm doing

**Comment by lordsrubka5** [comment]
what

**Comment by Travja** [comment]
Folders on the editor for organization.

**Comment by lordsrubka5** [comment]
just remove the skill when you are done editing it? and drag it back in when you need to fix it?

**Comment by goflishMC** [comment]
> I would really like if there is a way to add skills to categories just like a skill that would look like a skill but the text is bold and you can just drag and drop other skills under it so you know what they are I'm having a really difficult time managing all of the skills and keeping them in line and track of what I'm doing

This planned

**Comment by Tainted-Valor** [comment]
> just remove the skill when you are done editing it? and drag it back in when you need to fix it?

So the problem with that is I'm working on making so everything's like synchronized I have to go through each skill because they're not all finished and I'm just like adjusting everything slowly and it's just been like difficult I made a Google doc to keep it organized but it's still not great

**Comment by Tainted-Valor** [comment]
> > I would really like if there is a way to add skills to categories just like a skill that would look like a skill but the text is bold and you can just drag and drop other skills under it so you know what they are I'm having a really difficult time managing all of the skills and keeping them in line and track of what I'm doing
> 
> This is planned

Awesome

**Comment by goflishMC** [comment]
> I would really like if there is a way to add skills to categories just like a skill that would look like a skill but the text is bold and you can just drag and drop other skills under it so you know what they are I'm having a really difficult time managing all of the skills and keeping them in line and track of what I'm doing

did you know that you can make sub folders to organize your skills on your server? we're still going to add the feature you are talking about, I just wanted to make sure you can organize them on your server.

**Comment by goflishMC** [comment]
> > > I would really like if there is a way to add skills to categories just like a skill that would look like a skill but the text is bold and you can just drag and drop other skills under it so you know what they are I'm having a really difficult time managing all of the skills and keeping them in line and track of what I'm doing
> > 
> > 
> > did you know that you can make sub folders to organize your skills on your server? we're still going to add the feature you are talking about, I just wanted to make sure you knew that you can organize them on your server.
> 
> No I did not I'm not sure how I would go about doing that could you explain it to me or show me where to look into it?

https://i.imgur.com/lxi459r.png

you make a new folder in your skills folder

**Comment by Travja** [comment]
Closing this so we can track progress for this on #406
