### ISSUE TITLE
[Bug]: Buff mechanic doesn't work when you placing into damage triggers or uses Immediatly buff on them

### ISSUE THREAD

**Issue by Cerpevt** [promcteam/proskillapi#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Placing buff mechanic on triggers doesn't work. No difference is it immedialty or buff for x seconds - it just not work. But if you use buff mechanic on cast trigger - it's working

### Expected Behavior

When trigger for dealing damage activates, buff should increase incoming damage or if it's not immedaitly buff increase damage on x seconds

### Steps To Reproduce

1. Add to any damage trigger buff mechanic
2. Upload skill and class file
3. Test it

### Environment

```markdown
- Server Software: Paper 1.16.5
- ProSkillAPI Version: 1.1.7.18-20221202.073302-29
- ProMCCore Version: 1.0.3.10-20221202.072232-14
- Plugins: Proskillapi, ProMCCore, Essentials, MythicMobs, LuckPerms
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment]
I'm not experiencing this bug. Closing.
