### ISSUE TITLE
[Bug]: Defense stats from attributes do not work correct with ProRPGItems

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Per our (travja) conversation on Discord I have discovered an issue with the defense stats from attributes.

<pre>
#This allows you to check for damage causes on spigot
#With prorpgitems installed this will not lower defense
#Tested using this formula v-(a*0.05)
defense-TYPE

#This provides physical defense from basic attacks and projectile attacks.
#Tested using this formula v-(a*0.05)
#Without prorpgitems installed, this formula provides additional defense as expected
#With prorpgitems installed, no additional defense is given
physical-defense
</pre>

### Expected Behavior

defense-<type> and physical-defense should provide additional protection, which works fine unless prorpgitems is installed.

### Steps To Reproduce

1. Load up both proskillapi and prorpgitems.
2. Copy this attribute to your attributes.yml file in proskillapi: https://pastebin.com/aDSf9emz
3. Keep in mind, I put all 3 stats that I tested, but I did not test all 3 at the same time
4. Join a class and give yourself attribute points
5. Add points to the attribute class (Constitution in my example)
6. Using another account attack the player with the defense attribute
7. This will give you no damage change
8. Remove prorpgitems
9.  Using another account attack the player with the defense attribute
10. Without prorpgitems installed you should start getting the proper defense when attacked

### Environment

```markdown
- Server Software: paper 1.19.2
- ProSkillAPI Version: prorpgitems-1.0.3.17-SNAPSHOT
- ProMCCore Version: proskillapi-1.1.7.18-20221121.070512-25
- Plugins: https://i.imgur.com/NZ6uqr7.png
```

**Comment by Travja** [comment]
This should be resolved with the latest build of ProSkillAPI. With ProRPGItems installed, ProSkillAPI now has an option to modify damage done by each of ProRPGItem's damage types. In the stats section of the ProSkillAPI, simply specify `rpgdefense-TYPE` or `rpgdamage-TYPE` to specify a defense/damage buff respectively. It will automatically apply the `physical-defense` and `physical-damage` buffs to this damage as well (as well as projectile and melee ones if applicable). I feel like this is bound to have some kinks that will need to be worked out, but for the moment, this appears to work!
