### ISSUE TITLE
[Bug]: error with mmoitems when i cast a skill caused damage to the mobs

### ISSUE THREAD

**Issue by XKZC** [promcteam/proskillapi#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

The error message in the console:
[23:07:52 ERROR]: Could not pass event SkillDamageEvent to MMOItems v6.8.1
java.lang.NoSuchMethodError: 'void io.lumine.mythic.lib.damage.AttackMetadata.<init>(io.lumine.mythic.lib.damage.DamageMetadata, org.bukkit.entity.LivingEntity, io.lumine.mythic.lib.player.PlayerMetadata)'
        at net.Indyuce.mmoitems.comp.rpg.ProSkillAPIHook.a(ProSkillAPIHook.java:50) ~[MMOItems-6.8.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor940.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.sucy.skill.api.skills.Skill.damage(Skill.java:763) ~[proskillapi-1.1.7.18-20221202.073302-29.jar:?]
        at com.sucy.skill.dynamic.mechanic.DamageMechanic.execute(DamageMechanic.java:88) ~[proskillapi-1.1.7.18-20221202.073302-29.jar:?]
        at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:229) ~[proskillapi-1.1.7.18-20221202.073302-29.jar:?]
        at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:59) ~[proskillapi-1.1.7.18-20221202.073302-29.jar:?]
        at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:229) ~[proskillapi-1.1.7.18-20221202.073302-29.jar:?]
        at com.sucy.skill.dynamic.mechanic.ProjectileMechanic.lambda$callback$0(ProjectileMechanic.java:242) ~[proskillapi-1.1.7.18-20221202.073302-29.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1532) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps To Reproduce

just cast a skill to mobs or players and caused damage
Here is my test skill:
火焰弹: 
  name: '火焰弹'
  type: '主动'
  max-level: 1
  skill-req-lvl: 1
  needs-permission: 'false'
  cooldown-message: 'true'
  attributes: 
    level-base: '1'
    level-scale: '0'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '5'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'JACK_O_LANTERN'
  icon-data: 0
  icon-durability: 0
  icon-lore: 
  - '&d{name} &7({level}/{max})'
  - '&2类型: &6{type}'
  - ''
  - '{req:level}等级: {attr:level}'
  - '{req:cost}技能点消耗: {attr:cost}'
  - ''
  - '&2法力值消耗: {attr:mana}'
  - '&2冷却时间: {attr:cooldown}'
  desc:  []
  components: 
    Cast: 
      type: 'trigger'
      indicator: 'None'
      data: 
        icon-key: ''
      children: 
        Offset-b: 
          type: 'target'
          indicator: 'None'
          data: 
            icon-key: ''
            forward-base: '0'
            forward-scale: '0'
            upward-base: '1'
            upward-scale: '0'
            right-base: '0'
            right-scale: '0'
            group: 'enemy'
            wall: 'false'
            caster: 'false'
          children: 
            Projectile-c: 
              type: 'mechanic'
              indicator: 'None'
              data: 
                icon-key: ''
                counts: 'True'
                projectile: 'Ghast Fireball'
                flaming: 'False'
                cost: ''
                group: 'Enemy'
                spread: 'Cone'
                amount-base: '1'
                amount-scale: '0'
                velocity-base: '1'
                velocity-scale: '0'
                angle-base: '30'
                angle-scale: '0'
                position: '0'
                forward-base: '0'
                forward-scale: '0'
                upward-base: '1'
                upward-scale: '0'
                right-base: '0'
                right-scale: '0'
                use-effect: 'False'
              children: 
                Area-d: 
                  type: 'target'
                  indicator: 'None'
                  data: 
                    icon-key: ''
                    radius-base: '3'
                    radius-scale: '0'
                    group: 'Enemy'
                    wall: 'True'
                    caster: 'False'
                    max-base: '99'
                    max-scale: '0'
                    random: 'False'
                  children: 
                    Damage-e: 
                      type: 'mechanic'
                      indicator: 'None'
                      data: 
                        icon-key: ''
                        counts: 'True'
                        type: 'Damage'
                        value-base: '1'
                        value-scale: '1'
                        true: 'False'
                        classifier: 'default'
                      children:  {}
                    Particle-f: 
                      type: 'mechanic'
                      indicator: 'None'
                      data: 
                        icon-key: ''
                        counts: 'True'
                        particle: 'Huge Explosion'
                        arrangement: 'Hemisphere'
                        radius-base: '1'
                        radius-scale: '0'
                        particles-base: '3'
                        particles-scale: '0'
                        visible-radius: '25'
                        dx: '0'
                        dy: '0'
                        dz: '0'
                        speed: '1'
                        amount: '1'
                        forward: '0'
                        upward: '0.3'
                        right: '0'
                      children:  {}
                    Sound-g: 
                      type: 'mechanic'
                      indicator: 'None'
                      data: 
                        icon-key: ''
                        counts: 'True'
                        sound: 'Entity Enderdragon Fireball Explode'
                        volume-base: '100'
                        volume-scale: '0'
                        pitch-base: '1'
                        pitch-scale: '0'
                      children:  {}
                    Push-h: 
                      type: 'mechanic'
                      indicator: 'None'
                      data: 
                        icon-key: ''
                        counts: 'True'
                        type: 'Fixed'
                        speed-base: '1'
                        speed-scale: '0'
                        source: 'none'
                      children:  {}

### Environment

```markdown
- Server Software: Paper 1.18.2
- ProSkillAPI Version: proskillapi-1.1.7.18-20221202.073302-29
- ProMCCore Version: promccore-1.0.3.10-20221110.064223-9
- Plugins:
AntiCooldown, BetterStructures, Citizens, CMI, CMIEInjector*, CMILib, CoreProtect, FrameLooker, HolographicDisplays, JPremium, LuckPerms, MMOItems, Multiverse-Core, MythicLib, MythicMobs, NBTAPI, NeigeItems, NotQuests, OpenInv, PlaceholderAPI, ProMCCore, ProSkillAPI, ProtocolLib, Residence, ResourceWorld, Skins*, SkinsRestorer, TAB, TradePlus, TrMenu, TubeTils, Vault, ViaBackwards, ViaVersion, VoidTeleport, Vulcan, WkKit, WorldEdit
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by goflishMC** [comment]
> Please help me to clear this error message or should i ask help for mmoitems?

I'm not really sure what you are doing. Did you put a skill on your mmoitem?

**Comment by XKZC** [comment]
> > Please help me to clear this error message or should i ask help for mmoitems?
> 
> I'm not really sure what you are doing. Did you put a skill on your mmoitem?

no, i used skillapi to cast the skill

**Comment by goflishMC** [comment]
> > > Please help me to clear this error message or should i ask help for mmoitems?
> > 
> > 
> > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> 
> no, i used skillapi to cast the skill

What's your mmoitems version and mythicmobs version?

**Comment by XKZC** [comment]
> > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > 
> > > 
> > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > 
> > 
> > no, i used skillapi to cast the skill
> 
> What's your mmoitems version and mythicmobs version?
> 
> You also need to update your promccore
> 
> Also, it appears to be an issue with mmoitems, not our plugin.

all are the latest version,ok, i will ask help for them ,thanks for your answer

**Comment by goflishMC** [comment]
> > > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > > 
> > > > 
> > > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > > 
> > > 
> > > no, i used skillapi to cast the skill
> > 
> > 
> > What's your mmoitems version and mythicmobs version?
> > You also need to update your promccore
> > Also, it appears to be an issue with mmoitems, not our plugin.
> 
> all are the latest version,ok, i will ask help for them ,thanks for your answer
Your Promccore is not the latest version, look in our dev builds channel

**Comment by XKZC** [comment]
> > > > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > > > 
> > > > > 
> > > > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > > > 
> > > > 
> > > > no, i used skillapi to cast the skill
> > > 
> > > 
> > > What's your mmoitems version and mythicmobs version?
> > > You also need to update your promccore
> > > Also, it appears to be an issue with mmoitems, not our plugin.
> > 
> > 
> > all are the latest version,ok, i will ask help for them ,thanks for your answer
> > Your Promccore is not the latest version, look in our dev builds channel
fine..i updated it, but there still will be the same error message in the console

**Comment by goflishMC** [comment]
> > > > > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > > > > 
> > > > > > 
> > > > > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > > > > 
> > > > > 
> > > > > no, i used skillapi to cast the skill
> > > > 
> > > > 
> > > > What's your mmoitems version and mythicmobs version?
> > > > You also need to update your promccore
> > > > Also, it appears to be an issue with mmoitems, not our plugin.
> > > 
> > > 
> > > all are the latest version,ok, i will ask help for them ,thanks for your answer
> > > Your Promccore is not the latest version, look in our dev builds channel
> > > fine..i updated it, but there still will be the same error message in the console

I didn't mean that updating to latest would fix it, I was just letting you know it's outdated.

**Comment by XKZC** [comment]
> > > > > > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > > > > > 
> > > > > > > 
> > > > > > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > > > > > 
> > > > > > 
> > > > > > no, i used skillapi to cast the skill
> > > > > 
> > > > > 
> > > > > What's your mmoitems version and mythicmobs version?
> > > > > You also need to update your promccore
> > > > > Also, it appears to be an issue with mmoitems, not our plugin.
> > > > 
> > > > 
> > > > all are the latest version,ok, i will ask help for them ,thanks for your answer
> > > > Your Promccore is not the latest version, look in our dev builds channel
> > > > fine..i updated it, but there still will be the same error message in the console
> 
> I didn't mean that updating to latest would fix it, I was just letting you know it's outdated.
> 
> the problem with mmoitems



> > > > > > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > > > > > 
> > > > > > > 
> > > > > > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > > > > > 
> > > > > > 
> > > > > > no, i used skillapi to cast the skill
> > > > > 
> > > > > 
> > > > > What's your mmoitems version and mythicmobs version?
> > > > > You also need to update your promccore
> > > > > Also, it appears to be an issue with mmoitems, not our plugin.
> > > > 
> > > > 
> > > > all are the latest version,ok, i will ask help for them ,thanks for your answer
> > > > Your Promccore is not the latest version, look in our dev builds channel
> > > > fine..i updated it, but there still will be the same error message in the console
> 
> I didn't mean that updating to latest would fix it, I was just letting you know it's outdated.
> 
> the problem with mmoitems

ok

**Comment by XKZC** [comment]
> > > > > > > > Please help me to clear this error message or should i ask help for mmoitems?
> > > > > > > 
> > > > > > > 
> > > > > > > I'm not really sure what you are doing. Did you put a skill on your mmoitem?
> > > > > > 
> > > > > > 
> > > > > > no, i used skillapi to cast the skill
> > > > > 
> > > > > 
> > > > > What's your mmoitems version and mythicmobs version?
> > > > > You also need to update your promccore
> > > > > Also, it appears to be an issue with mmoitems, not our plugin.
> > > > 
> > > > 
> > > > all are the latest version,ok, i will ask help for them ,thanks for your answer
> > > > Your Promccore is not the latest version, look in our dev builds channel
> > > > fine..i updated it, but there still will be the same error message in the console
> 
> I didn't mean that updating to latest would fix it, I was just letting you know it's outdated.
> 
> the problem with mmoitems

ok
