### ISSUE TITLE
[Bug]Scoreboard not working

### ISSUE THREAD

**Issue by RebelRanger** [promcteam/proskillapi#43]
**Describe the bug**
When loading into a 1.17.1 server running ProSkillAPI 1.1.6 the skill scoreboard does not appear.

**To Reproduce**
Run 1.17.1 server.
Join server and profess into a class.
See error message in console.

**Expected behavior**
Scoreboard should appear with various stats.

**latest.log**
https://pastebin.com/LsZLxLgd

**Versions (please complete the following information):**
-  Spigot Version: paper 1.17.1-116
 - Server Version: 1.17.1
 - Plugin Version: 1.6.1

**Comment by goflishMC** [comment]
This is working on our latest version (not yet released, I'm going to close this ticket)
