### ISSUE TITLE
[Bug]: Skill changes based on viewing position 

### ISSUE THREAD

**Issue by myoungho-jung** [promcteam/proskillapi#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

The skill is different when you cast the skill looking down and when you cast the skill looking straight ahead

For example, the same goes for the cone on target. If I look down, the monster on the front is not damaged

![11](https://user-images.githubusercontent.com/64332634/206290075-e76ae2b1-bbca-4f7c-9de0-8e6a0b58848a.png)
![22](https://user-images.githubusercontent.com/64332634/206290086-ede926d4-c483-443d-8674-cbd23dfa41e6.png)

If you look at the front, the skill is activated as I made it. But if you look diagonally or downward, your skills will be ruined

If it's not a bug, you always need the option to activate the skill at a fixed look pitch.

If it's not a bug, we need the option to try the skill at a fixed look pitch

### Environment

```markdown
last version plugin

purpur-1.19.2-1845
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```ㅇㅇ

</p>
</details>


### Anything else?

_No response_

**Comment by Travja** [comment]
Added option to reset yaw for Block Mechanic. Use that to produce the desired results.
