### ISSUE TITLE
[Bug] Direction Launch Option

### ISSUE THREAD

**Issue by Tanis468** [promcteam/proskillapi#444]
Currently the Launch mechanic only propels a target/caster in the direction their body is facing, not their head (screen), and the Between function for Launch can't launch the Caster relevant to a Target, just a Target relevant to the Caster.
This means it is currently impossible to create a skill that allows the Caster to propel themselves in the direction they are looking.
An option that allows Launch to pull the the precise direction Caster (And I guess Target too) is looking, would enable the creation of proper leaping skills

**Comment by lordsrubka5** [comment]
Are you sure? From what I am aware of the launch mechanic works based on angle of looking since that is stored in "yaw", I highly doubt it would try to do some shinanigans with body rotation since I have never heard of it being used anywhere

**Comment by Tanis468** [comment]
It's what all my testing has shown. Half the time I'm flying off at a 45 degree angle to where I'm looking in flat terrain (nothing to bounce off), and when watching from an external perspective, it's always been wehre my body was facing.
For whatever reason, the outcome seems to be amplified in water (even when standing in it normally), so it's even easier to see under those conditions.

**Comment by RebelRanger** [comment]
Yeah, would love to see this implemented. The current system makes mobility/leaping skills very difficult to do well.

**Comment by lordsrubka5** [comment]
I tested using my roll skill from tutorials, it sends me in the direction where im looking
![image](https://user-images.githubusercontent.com/74104790/219900688-893816e3-219f-476a-a5c4-6f9b43104872.png)
![image](https://user-images.githubusercontent.com/74104790/219900697-4b02273a-b7f0-4590-921d-4a4e922f58a3.png)
![image](https://user-images.githubusercontent.com/74104790/219900716-c9c8959b-014e-4113-b1cb-706e7057ebb2.png)

**Comment by Travja** [comment]
To my knowledge, the server actually has no knowledge of which direction the player's body is facing. It should actually be rendered and determined client-side. This is why sometimes you can get some weirdness happening where the player's head is pointing an entirely different direction from their body. Regardless, Spigot's yaw and pitch are indeed determined by the head direction. If you're experiencing a launch in a different direction, there must be something else interfering.

**Comment by lordsrubka5** [comment]
What version and server software are you using? Is the server modded?

**Comment by Tanis468** [comment]
Perhaps it is just a lag issue then. It stood out to me because I encountered the issue on two entirely unrelated (and un-modded) servers with different versions and different plugin suites, yet the issue of Launch not _always_ sending me in the right direction persisted with identical behaviour.
One thing that I did find though, the issue was always 100% re-creatable when in water, regardless of any physical blocks in the vicinity. You'd just go flying off in the wrong direction, the common factor would always be that the direction matched the facing of the playermodel's torso.

One question though, if it is bound to the head, why is the mechanic locked only to the Yaw axis? The Pitch of the head makes no identifiable difference to the launch direction, at least in my experience anyway. (Which is partly why I believed this was an issue of torso facing, as that part of the model is solely locked to a Yaw rotation.)
Wouldn't access to Pitch axis be a useful option for Launch skills requiring more directional precision?

**Comment by Tanis468** [comment]
Mis-clicked, ignore that ^

**Comment by Travja** [comment]
Because we allow setting the upward velocity manually, pitch wouldn't have any effect anyway. We could potentially adjust the mechanic to allow the player's pitch to take effect there. But for now, pitch is ignored and the upward velocity is used instead.

Could you send your skill that you're seeing this behavior with?

**Comment by Tanis468** [comment]
An option to make Pitch useable would be ideal. The Upward velocity mechanic is useful! But there are cases where it's not.

Sent you the files in Discord as GitHub doesn't support YML files.

**Comment by Tanis468** [comment]
https://drive.google.com/file/d/1U7GQFhouwH5iB3n98lOBte9tfjlu_4VQ/view?usp=sharing

NVM. Just uploaded them to Google Drive instead. There should be two in there, I experienced the same problem with both.

**Comment by Travja** [comment]
![Vault](https://user-images.githubusercontent.com/1574947/220808677-2f49d3b1-c987-4fb0-905e-70bff217be16.gif)
Your skill works great for me? What version of ProSkillAPI are you using? And what Spigot version are you using?

**Comment by Tanis468** [comment]
I'm no longer working on the Project that was going to use that water skill, so I genuinely don't remember and don't have access to the server to check. It was just a good example of the problem in an older version.
It's looking more likely that it was a server-side issue not a plugin one. I can't get the other skill to reliably dysfunction, so it's probably poor connection.

Definitely still putting forward the suggestion for adding a Pitch option to Launch, but I'm probably going to say this issue is resolved. Thanks for the help.

**Comment by Travja** [comment]
Cool. No problem. Thanks for your communication!

**Comment by lordsrubka5** [comment]
> An option to make Pitch useable would be ideal. The Upward velocity mechanic is useful! But there are cases where it's not.

Is already possible by playing around wit math and values but making it more simpler might be nice
