### ISSUE TITLE
[Enhancement] Add a Condition for BlockBreak or Trigger in Editor

### ISSUE THREAD

**Issue by killer5362** [promcteam/proskillapi#447]
**Is your feature request related to a problem? Please describe.**
https://discord.com/channels/818973833570680882/1062179703982657686/1062179703982657686

**Describe the solution you'd like**
Add a condition to the online editor to do child components based on what trigger was triggered.

**Describe alternatives you've considered**
Use a passive and the Trigger Mechanic to achieve the wanted results

**Comment by Travja** [comment]
This can be done by selecting multiple block types from the BlockBreakTrigger and using a condition testing the `api-block-type` value against the material from [this list](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
