### ISSUE TITLE
[Bug] Tools Conditions page in the editor lacks Netherite as a Material type

### ISSUE THREAD

**Issue by Zicerite** [promcteam/proskillapi#45]
**Describe the bug**
Tools Condition page in the editor not updated in 1.17 to have Netherite as a Material type.

**To Reproduce**
1. Go to the editor
2. Click on Tools under Conditions
3. Select Materials; Netherite doesn't exist

![image](https://user-images.githubusercontent.com/30883277/126378658-0c8846ec-3a72-420b-a099-3f265de3b163.png)

**Expected behavior**
Netherite expected to exist under Material.

**latest.log**
No Log for this bug.

**Versions (please complete the following information):**
-  Spigot Version: 1.17.1-3183
 - Server Version: 1.17.1
 - Plugin Version: 1.1.6-dev-build

**Additional info**
None.

**Comment by Travja** [comment]
Does Netherite appear under 1.16?

**Comment by goflishMC** [comment]
> Does Netherite appear under 1.16?

I just tested this, it does not show up under 1.16 either

**Comment by Travja** [comment]
Should be fixed.
