### ISSUE TITLE
[Enhancement] Provide color code for potion projectile instead of selecting type

### ISSUE THREAD

**Issue by penswen** [promcteam/proskillapi#453]
**Is your feature request related to a problem? Please describe.**
Most of the potion options for potion projectile don't actually work and even if they did, are restrictive.

**Describe the solution you'd like**
Let users set the RGB/hex color code of the fired potion in the editor. Allows for more diverse potion projectiles.

**Describe alternatives you've considered**
Making all potions projectiles of the few types that work

**Additional context**
Refer to issue #452 for additional details about potion projectile issues.

**Comment by Travja** [comment]
Implemented in latest build, going out in a couple of mins.
