### ISSUE TITLE
[Enhancement] Add 'World' target option

### ISSUE THREAD

**Issue by StarkyOficial** [promcteam/proskillapi#46]
**Describe the bug**
I tried to deal damage to every player in the world, so if they get killed... the chat says the player that casted the skill killed them.
I set an Area of 800 blocks with some Damage.

But when I cast the skill, the server freezes/crashes. I tried the Nearest target one aswell.

**To Reproduce**
![image](https://user-images.githubusercontent.com/86807670/126528160-c9055b7c-e0f2-43b3-b7b0-e2664405e267.png)

**Expected behavior**
Deal damage to every player inside a very large area, and if the skill killed someone, it should show the kill messages on the chat saying that the {caster} killed {target}.

**latest.log**
https://pastebin.com/bBrQjhi5

**Versions (please complete the following information):**
-  Spigot Version: git-Tuinity-"3eda860"
 - Server Version: (MC: 1.16.5)
 - Plugin Version: PROSKILLAPI-Alpha-1.1.6

**Additional info**
Maybe adding a new "World" Target could we get this to work?

**Comment by Travja** [comment]
Targeting a radius of 800 blocks is sure to cause some issues regardless of the context involved. That being said, adding a world target would be a good alternative to this as it is much easier to get entities/players in the world as opposed to mathematically calculating if entities are within range as this uses a lot of computational resources.

**Comment by StarkyOficial** [comment]
Yeah, that would be amazing and really useful.
