### ISSUE TITLE
Remove integrated Quests module

### ISSUE THREAD

**Issue by PikaMug** [promcteam/proskillapi#461]
Please remove the module included in your plugin. According to a [recent review](https://www.spigotmc.org/resources/quests.3711/reviews#review-492191-1512644), it is not functional. While updating it is an option, version 5.0.0 of Quests will surely break it again. I would be happy to maintain an external module for Proskillapi should you opt for removal.

**Comment by Travja** [comment]
Hey PikaMug! Thanks for reaching out. If you're willing to maintain a module for ProSkillAPI support, that would be awesome!

**Comment by PikaMug** [comment]
@Travja Hey, thanks for the quick response. Sure thing, it would be no trouble. Feel free to tag me here or join the Quests discord once you're ready to publish with the integration disabled/removed.

**Comment by PikaMug** [comment]
Hi @Travja, following up on this. Would you like me to submit a PR to remove integration?

**Comment by Travja** [comment]
Sorry. I guess the biggest question I have is just what direction Wed need to give users that currently rely on that built-in integration? I just want to make sure the transition is as smooth as we can make it.

**Comment by PikaMug** [comment]
@Travja No worries. If we go by the date of [this ticket](https://github.com/PikaMug/Quests/issues/301), then integration has been broken since 2018, well before the release of Proskillapi. So unless there's some kind of workaround, removal should not affect any of your users.

**Comment by Travja** [comment]
Our internal Quests module works to my knowledge. It's hosted on @SparkGNRK's page. I guess the reason to move forward with the removal would be if the current implementation has fundamental issues and would be better kept up by yourself so we always maintain api compatibility.

**Comment by PikaMug** [comment]
@Travja Unfortunately, as I mentioned, it is not functional per [this review](https://www.spigotmc.org/resources/quests.3711/reviews#review-492191-1512644).

**Comment by PikaMug** [comment]
Apparently this was fixed in the April 25th update to Proskillapi!
