### ISSUE TITLE
[Bug] 2 Bugs inside

### ISSUE THREAD

**Issue by bloggy** [promcteam/proskillapi#47]
**Describe the bug**

- Mechanic "command" does not return correct target, UUID of target (but instead returns caster's UUID and name): https://i.imgur.com/5HmJO5r.png (I have targeted a mob). From the editor: https://i.imgur.com/zocvYMd.png
- Console error when I join my server: https://paste.gg/p/anonymous/df138f711ec445aea70255ff3b85c678/files/88af715246274788880ca236044e86d4/raw

**Versions (please complete the following information):**
 - Server Version: This server is running Tuinity version git-Tuinity-23 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ce43ccd on HEAD)
 - Plugin Version [11:43:26] [Server thread/INFO]: [SkillAPI] Loading SkillAPI vs1.99

**Comment by Travja** [comment]
Regarding the console error on joining, we're working on an update for 1.17 that fixes scoreboards and stuff. A lot of things on the backend of how Minecraft operates were changed from 1.16 to 1.17, so we're having to adjust and it's not always clear what needs  to be updated.

As far as the command mechanic, we'll take a look at that shortly.

**Comment by goflishMC** [comment]
Can you post the skill you are trying to use?

**Comment by goflishMC** [comment]
I just tested this with our new build (not yet released) https://i.imgur.com/F7RmXOy.png

and this was the result: https://i.imgur.com/bdP8Npj.png

This is my UIID: https://i.imgur.com/gUSiWTi.png

It does not match the UUID posted, I targeted a mob with this skill. I'm closing this issue, seems to be fixed.
