### ISSUE TITLE
[Enhancement] Text Condition

### ISSUE THREAD

**Issue by blackquiver** [promcteam/proskillapi#479]
ProSkillAPI is often used to create magical skills or systems. I think that introducing a 'text' condition, if at all possible, would expand the possibilities in these systems.

Check for a single word, phrase, or regex string within what someone says would then activate the children conditions/mechanics.

A condition like this would allow for the creation of magical systems, or much more involved skill casting for things like bard classes, or shout-based classes and skills.

**Comment by Travja** [comment]
This was actually implemented as a Chat trigger in #534, at least how I've interpreted things happening. The associated ValueTextCondition in #538 could be used in combination with the ChatTrigger to further whittle down the requirements for various effects to happen
