### ISSUE TITLE
[Bug]: Physical Damage Trigger and Damage Mechanic

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Physical damage trigger will pick up on all spigot damage causes that are not custom. I think it should only pick up on entity attack, sweep attack and whatever is for bow instead of all other things like cramming, fire, drowning and so on

### Environment

```markdown
-
```

**Comment by Sentropic** [comment]
How about we add an option in the editor where you select which DamageCauses should be considered? Obvs default to all except CUSTOM to not break existing skills.

**Comment by Sentropic** [comment]
Duplicate of #477
