### ISSUE TITLE
[Bug]: Cannot assign skills to slot.

### ISSUE THREAD

**Issue by cattysama** [promcteam/proskillapi#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Here is a GIF https://s2.loli.net/2023/06/30/Tn7hm1Fb5pvdaDc.gif
Slot that are Unassigned in game often make mistakes that are inconsistent with the layout in config, such as the icon will disappear and wrong slot layout.

### Expected Behavior

I hope it can be assigned to the unassigned icon.

### Steps To Reproduce

I made these changes (only partially) in the config.
```
Casting: 

  enabled: 'false'

  bars: 'false'

  combat: 'false'
```
...

```
Skill Bar: 

  enabled: 'true'

...

  layout: 
    1: 
      skill: 'true'
      locked: 'false'
    2: 
      skill: 'true'
      locked: 'false'
    3: 
      skill: 'true'
      locked: 'false'
    4: 
      skill: 'true'
      locked: 'false'
    5: 
      skill: 'true'
      locked: 'false'
    6: 
      skill: 'false'
      locked: 'false'
    7: 
      skill: 'false'
      locked: 'false'
    8: 
      skill: 'false'
      locked: 'false'
    9: 
      skill: 'false'
      locked: 'false'
```

### Environment

```markdown
- Server Software:spigot 1.20.1
- ProSkillAPI Version:the latest
- ProMCCore Version:the latest
- Plugins:
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

My English is poor, and there may be mistakes in grammar or words. I use translation software. I come from China, and it is very difficult to contact you by discord, which is a pity.Anyway, you took over Skillapi and did a great job.

**Comment by goflishMC** [comment]
Can you please put the actual version numbers and not just, "latest". We also need your latest.log. (stop your server, start your server, then stop it again and then upload the latest.log)

thanks!

**Comment by cattysama** [comment]
> Can you please put the actual version numbers and not just, "latest". We also need your latest.log. (stop your server, start your server, then stop it again and then upload the latest.log)
> 
> thanks!

- ProSkillAPI Version:ProSkillAPI 1.1.8-R0.32
- ProMCCore Version:ProMCCore 1.0.4-R0.12-SNAPSHOT
This is the latest log, but ProSkillApi didn't report an error.
[latest.log](https://github.com/promcteam/proskillapi/files/11913237/latest.log)

**Comment by Travja** [comment]
So the main issue I'm seeing here is that you can't assign skills to the hotbar. The reason for this is that only **castable** skills can be assigned to the hotbar. This means that they should have a `Cast` trigger on them. Left/right click aren't valid triggers and can't be assigned this way.

If you have any other problems surrounding this, we can reopen the ticket, but for now I'm going to close this.
