### ISSUE TITLE
[Enhancement]Values between restarts/reconnect 

### ISSUE THREAD

**Issue by Demonyte** [promcteam/proskillapi#482]
Please add an mechanic to save and load values into a file to server, using player's UUID. For example
"Mechanic: Value save"
You add this mechanic into cleanup trigger and put inthere a value, also give it an custom name, that you want to save into file, so you can use it anytime you want, even between server restart, so you can create some custom progress skill mechanics.
Also "mechanic: value load"
You can put this on any trigger, usually on Initialise, to load an value assigned to a player from server's file, so you can use that presaved value any time you want.
As target you can give it any player target, and if there are values saved for that target, it can be loaded from server's file using it's player UUID.
Also as an addition you can add an "mechanic: value clear" to clear saved value from server's file. 
Like i said, values can be stored using a custom name and player's UUID, so they will be unique for each player. Just like an "value set" but used for setting and loading values between restarts, so they are not removed each time you relogin.

**Comment by Travja** [comment]
Added via Value Load Mechanic and save options on the various value mechanics.
