### ISSUE TITLE
[Bug]: Editor File Recognition When Empty

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

If a skill has no mechanics and uploaded into the editor again, it gets recognized as a class instead.
Tested both on old and new editor

### Environment

```markdown
-
```

**Comment by Travja** [comment]
@lordsrubka5 I'm actually not seeing this behavior... Do you have an example skill I can try?

**Comment by Travja** [comment]
Can't reproduce
