### ISSUE TITLE
[Enhancement]: Backup All Data Button

### ISSUE THREAD

**Issue by killer5362** [promcteam/proskillapi#496]
**Is your feature request related to a problem? Please describe.**
In the old editor, there is a backup all data button in the top right which saves classes.yml and skills.yml . This is no longer available in the new editor.

**Describe the solution you'd like**
Please re-add this function.

**Describe alternatives you've considered**
you can only save it individually

**Additional context**

![Screenshot 2023-07-27 173314](https://github.com/promcteam/proskillapi/assets/47478901/0b69bf46-d1c0-4af4-97f6-6d53269a4d65)
![Screenshot 2023-07-27 173406](https://github.com/promcteam/proskillapi/assets/47478901/4202ef89-eb28-47f5-8e54-4e38ed3fb589)

**Comment by Travja** [comment]
For clarity, the button exists but the functionality does not.
