### ISSUE TITLE
[Enhancement] ArmorEquip Trigger

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#497]
Description: Applies child components when placing armor into the armor slots and items into the offhand slot.

<pre>
mana: true/false
cooldown: true/false
#tooltip for armor-slot: 1 = Head, 2 = Chest, 3 = Leggings, 4 = Boots, 5 = Offhand, 6 = Mainhand
armor-slot: 1-4
</pre>

Add this trigger to the trigger mechanic

**Comment by Sentropic** [comment]
Solved by 93cb2cef1796ee107a0fcd321748c7f3d22c7523, https://github.com/promcteam/promccore/commit/f40819dcc73bc6e7d0f5edce18dae0153eff2ce3 and https://github.com/Travja/editor/pull/142/commits/f3f17ff7b70804a77a6d42dbf673bd94d45a612f
