### ISSUE TITLE
[Enhancement]Armor stand projectile

### ISSUE THREAD

**Issue by Kajjou** [promcteam/proskillapi#5]
**This feature would be a great enhancement to the Skill Api plugin and community from my opinion**
How I plan on using it : making custom 3d models, armoring them to armor stands (on head for example) and then make projectiles to make skills and possibilities (creativity) go even further then particles, projectiles or item projectiles. It's already possible with item projectiles and changing the display on drop but it's not really convenient since item projectile shoots a dropped item that has this rotation motion and the hitbox/visual effect is meh. Display is basically bad. 
With armor stand projectile you could pretty much launch insane big models or even have more functions attached to it, like making it float and rotate around you : everything is pretty much possible.
I could try making an example of what I would like to see on SKillApi and how good it can eventually be ! 

On MagicSpells you can make this kind of stuff and it's actually pretty cool ! 
You launch this projectile spell https://github.com/TheComputerGeek2/MagicSpells/blob/4.0/core/src/main/java/com/nisovin/magicspells/spells/instant/ProjectileSpell.java

And you can add this effect 
https://github.com/TheComputerGeek2/MagicSpells/blob/4.0/core/src/main/java/com/nisovin/magicspells/spelleffects/effecttypes/ArmorStandEffect.java

**Comment by goflishMC** [comment]
Are you talking about making a new mechanic called "Armorstand Projectile"?

**Comment by Sentropic** [comment]
Most of this is already possible using the existing Armor Stand mechanic, since you can apply child components to it. You can launch it, warp it, make it target nearby entities as it moves, etc.
