### ISSUE TITLE
[Enhancement] heal trigger

### ISSUE THREAD

**Issue by fructozer** [promcteam/proskillapi#502]
**Is your feature request related to a problem? Please describe.**
I want to create a skill that is activated when the player receives healing.

**Describe the solution you'd like**
just add healing trigger

**Describe alternatives you've considered**
i have no idea

**Comment by TheKot1k** [comment]
We really need this

**Comment by fructozer** [comment]
Mana: true/false
Cooldown: true/false
Min heal: double
Max heal: double
