### ISSUE TITLE
[Bug] Selecting between Class/Skill

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#509]
In the sidebar if you have the class tab selected and click on save file you get the class file you have selected.

However, if you click on the skills tab and then click on the save file button it will save the last class file you had active.

What should happen: If you select the skill tab after having the class tab active it should set the the first skill in the skill tab as the active selection, so that when you click on the save button you are getting the skill file instead of the class file.

Steps to reproduce:
1. Create 1 class
2. Create 1 skill
3. Click on the class tab and select a class
4. Click on the save button in the bottom right
5. Now click on the skill tab
6. Click on the save button in the bottom right
7. You will get the last class file you had active instead of a skill from the skill tab

This was done in firefox on windows

**Comment by Travja** [comment]
I'm actually a little on the fence about this. The save button saves the skill/class that is open. But I don't feel like just because you changed tabs, it should open one of the skills/classes there. What if we just wanted to open up the classes tab for reference?
