### ISSUE TITLE
[Bug] "Player Placeholders" and "Group Placeholders" not working

### ISSUE THREAD

**Issue by Arkhnen** [promcteam/proskillapi#51]
**Describe the bug**
"Player Placeholders" and "Group Placeholders" do nothing.

**To Reproduce**
Parse any "Player Placeholders" or "Group Placeholders". They can be found here:
https://promcteam.com/wiki/index.php?title=Proskillapi:Placeholders

Parsing them does nothing:
![image](https://user-images.githubusercontent.com/46220705/127163926-114e21a5-d6a4-48c8-8bed-5d06bd1bdd4b.png)

**Versions (please complete the following information):**
-  Spigot Version: Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Server Version: 1.16.5
 - Plugin Version 1.1.5-dev
 - PAPI Version: PlaceholderAPI-2.10.9.jar

**Comment by Travja** [comment]
Our wiki appears to be a little inaccurate at the moment. A couple of those placeholders are group placeholders and should start with `%sapi_group...` instead of `%sapi_player...` That still doesn't explain why the player ones are not working properly though. We'll have to look into that.

**Comment by goflishMC** [comment]
> **Describe the bug**
> "Player Placeholders" and "Group Placeholders" do nothing.
> 
> **To Reproduce**
> Parse any "Player Placeholders" or "Group Placeholders". They can be found here:
> https://promcteam.com/wiki/index.php?title=Proskillapi:Placeholders
> 
> Parsing them does nothing:
> ![image](https://user-images.githubusercontent.com/46220705/127163926-114e21a5-d6a4-48c8-8bed-5d06bd1bdd4b.png)
> 
> **Versions (please complete the following information):**
> 
> * Spigot Version: Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
> * Server Version: 1.16.5
> * Plugin Version 1.1.5-dev
> * PAPI Version: PlaceholderAPI-2.10.9.jar

I confirmed this is fixed in the latest dev builds
