### ISSUE TITLE
[Bug] Icon Lore in Classes Not Getting Registered In game

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#511]
This is the icon lore in the editor: https://i.imgur.com/fQwVOmC.png
This is the icon lore in game: https://i.imgur.com/85IIujY.png

Needs to be fixed

**Comment by Travja** [comment]
Are there any errors on startup or anything?

**Comment by Travja** [comment]
@goflish, with the new editor build, can you test to see if this is working now?
