### ISSUE TITLE
[Enhancement] Add random option in cast trigger

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#514]
<pre>
Icon Key:
Counts as Cast: true/false
#If true, each time this is called it would cast a skill from the list at random
random: true/false
#If only one skill listed, then that skill will cast each time this mechanic is called
Skills: list of skills
</pre>

**Comment by fructozer** [comment]
This will need to interfere deeply with the plugin's code. It would be better to have someone more experienced undertake this project to avoid a bad situation

**Comment by fructozer** [comment]
Force cast: true/false
- false: remove all unavailable skill with target from skill list then cast random
- true: just remove skills that don't exist and force players to cast random. In case the player has not learned this skill, the skill will be casted with level 1
