### ISSUE TITLE
[Enhancement] Add edible materials to data generator

### ISSUE THREAD

**Issue by Travja** [promcteam/proskillapi#517]
We need to add an entry for consumable materials to the item generator so we can more easily maintain lists of consumable materials for the new ConsumeTrigger and for potential future use cases. The `Material` enum has an `isEdible` method that we can use when doing the data generation in order to ensure we're getting all the proper materials.

Associated PRs: Travja/editor#138, #512, #516

**Comment by fructozer** [comment]
Potion and milk bucket is marked as not `isEdible`

**Comment by Travja** [comment]
Haha oops. Tagged the wrong thing
