### ISSUE TITLE
[Enhancement] Component group

### ISSUE THREAD

**Issue by fructozer** [promcteam/proskillapi#524]
**Problem:** The number of components is increasing, which makes it increasingly difficult to find what you need.
So I propose grouping some components into a group that displays as a dropdown list.

**Recommended groups: **
//trigger//
- Damage: Environment Damage, Physical Damage, Skill Damage, Took Physical Damage, Took Skill Damage
- Fishing: Fishing, Fishing Bite, Fishing Fail, Fishing Grab, Fishing Ground, Fishing Reel
- Item: Item drop, Item swap, armor equip 
- Block: Block break, Block place

//Mechanic//
- Value: Value Add, Value Atribute, Value Copy, Value Distance, Value Health, Value Location, Value Lore, Value Lore Slot, Value Mana, Value Multiply, Value Placeholder, Value Random
- Warp: Warp, Warp Location, Warp Random, Warp Swap, Warp Target, Warp Value
- Flag: Flag, Flag Clear, Flag Toggle
- Target: Remember Targets, Forget Targets

**Comment by Travja** [comment]
I'm not sure about drop-downs, but potentially have some sub-groups on things could be beneficial for helping people find things. I have toyed with the idea of making the larger component groups collapsible too.

**Comment by fructozer** [comment]
I don't understand what sub-groups really are. But as long as it benefits my eye longevity, it's great

**Comment by Sentropic** [comment]
We're working on making a single Value Mechanic that contains all functionality from the old ones, that's ought to help a bit at least.

**Comment by goflishMC** [comment]
I'll use the targets, conditions, and mechanics as an example.

<center>test</center>
