### ISSUE TITLE
[Bug]: Maxlevel placeholder doesn't work

### ISSUE THREAD

**Issue by marzifu** [promcteam/proskillapi#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

I was testing the placeholder on a scoreboard, I tried almost all of the placeholder but the %sapi_default_maxlevel% doesn't work somehow even with reloads and restart

### Expected Behavior

Should've shown the selected class max level, but instead it just shows the placeholder name

### Steps To Reproduce

I am using SimpleScore as the scoreboard
1. Use the %sapi_default_maxlvl% placeholder

### Environment

```markdown
- Server Software: Paper Spigot 1.20.1
- ProSkillAPI Version: 1.1.10-R0.8
- ProMCCore Version: 1.0.6-R0.5
- Plugins: SimpleScore + PSAPI
```

### latest.log

-

### Anything else?

-

**Comment by Travja** [comment]
It's either `default_currentmaxlevel` or it's `group_<GROUP NAME>_maxlevel`
