### ISSUE TITLE
[Bug]:  Incompatible feature not working / leading same combo for incompatible skill not working (?)

### ISSUE THREAD

**Issue by quidditch-newbie** [promcteam/proskillapi#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

Major: 
1. Incompatible setting among skills doesn't work. Once loaded into game, incompatible section in the yml of skills disappear thus making no restriction of skill acquiring in game.
2. Maybe bug maybe just intended behaviour, currently same pattern of combo of skills will cause only one of them works. Say skill A, B, C all has same pattern of combo, but only skill A can be casted with such combo even only one of them is learnt and are supposed to be restricted by incompatible feature.

Minor: 
1. Skills' yml containing incompatible section uploaded to online editor will not show incompatible info in online editor.

### Expected Behavior

Major:
1. After reloading the plugin, it should keep the incompatible of skills section.
2. Skills have same pattern of combo and incompatible to each other, all should keep effectiveness. So players can use such combo while are prevented from learning same pattern of combo of skills by incompatible setting.

Minor:
1. Skills' yml containing incompatible section uploaded to online editor should keep and show incompatible info in online editor.

### Steps To Reproduce

1. Upload to proskillapi/dynamic/skill
2. Reload the plugin

### Environment

```markdown
- Server Software: Paper Spigot 1.19.2
- ProSkillAPI Version: 1.1.10-R0.14-20230915.023545-1
- ProMCCore Version: 1.0.6-R0.6-20230824.060222-1
- Plugins: Essentials, PlaceholderAPI, ProMCCore, ProSkillAPI (SkillAPI), TAB
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

### Anything else?

Issue major #1 and minor #1 confirmed by staff in discord.
https://discord.com/channels/818973833570680882/1151023920896553080

**Comment by Travja** [comment]
Major 2 should be out in a separate ticket and explained in further detail
