### ISSUE TITLE
[Config]

### ISSUE THREAD

**Issue by Daisidaisy** [promcteam/proskillapi#55]
#1 Add config toggle cooldown skill on chat!
#2 language.yml currently doesn't have the Message of command /class exp, can you add it
and config toggle it

**Comment by goflishMC** [comment]
# Whether or not messages should be shown on casting a skill
  show-messages: 'true'

 # If "show-messages" is set to true add a cooldown so the message is not spammed for the same skill
 show-messages-cooldown: '<amount>'

**Comment by Sentropic** [comment]
Done in https://github.com/promcteam/proskillapi/commit/3566f45e9c2c54dc3dc152a314700ce5759a0e62
