### ISSUE TITLE
[Bug]: Particle

### ISSUE THREAD

**Issue by ronyan149** [promcteam/proskillapi#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

1.The particle effect of the mechanic projectile is faulty and doesn't display any particles.
2.In the mechanics particle section, two sub-items like "points" and "speed" are set by default to some fixed values. When I change the values of these two items, the particle quantity and speed don't change.

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:1.1.12-R08
- ProMCCore Version:1.1.0-R04
- Plugins:Paper Plugins:
  - EconomyShopGUI, ProMCCore, ProRPGItems, ProSkillAPI
 Bukkit Plugins:
  - AdvancedPortals, ajLeaderboards, anticmath, AuthMe, ChatEx, Citizens, CoinsEngine, DeluxeMenus, Essentials, EssentialsSpawn
  ExcellentCrates, Factions, HoloMobHealth, InvSeePlusPlus, LeaderMobs, LibsDisguises, LiteSignIn, LuckPerms, LWC, MarketPlace
 Multiverse-Core, MythicMobs, NexEngine, PlaceholderAPI, ProEnchantmentAPI, ProEnchantmentPack, ProHolographicDisplays, ProtocolLib, RaidsPerRegion, RocketPlaceholders
 Shopkeepers, SilkSpawners, SkinsRestorer, spark, TAB, Thesieutoc, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

**Comment by Travja** [comment]
Speed likely isn't what you'd expect it to be. Some particles (like smoke, for example) have a speed that they move away from their spawning point. This isn't the speed of the projectile itself. I haven't heard any other reports lately about particles not working. I'm going to go ahead and close this. If you're still running into issues, please create a post on Discord for more of a discussion.
