### ISSUE TITLE
[Trigger Additions]

### ISSUE THREAD

**Issue by TheZBlade** [promcteam/proskillapi#58]
**Is your feature request related to a problem? Please describe.**
While the current triggers are nice, having some more options would be great (I understand some of the options I suggest may have slight overlap with current features, but as long as users are aware, that shouldn't be an issue)

**Describe the solution you'd like**
Multiple new triggers, primarily left or right click, but any others beyond that would be very nice too, I'm currently trying to make a spell that triggers on every left click, whether the player hits a target or not, as well as a spell that can fire off shots with right clicks.

**Describe alternatives you've considered**
I've tried playing around with the current triggers and conditions to find the best way to mimic the ability with the current limitations of the plugin but was unable to find a satisfactory way of doing it, the only one that worked similarly was with crouch triggers, which is somewhat janky

**Additional context**
N/A

**Comment by Travja** [comment]
Left/Right click triggers have been added a while ago
