### ISSUE TITLE
[Enhancement] Custom Model Data Projectile Mechanic

### ISSUE THREAD

**Issue by iSoulEs** [promcteam/proskillapi#599]
add the function of putting custom model data to these projectiles, since the animation when launching in item projectile is different from  Projectile Mechanic.
![image](https://github.com/promcteam/proskillapi/assets/83812194/e73542f1-e977-4822-a7f5-150ad0523f7a)

**Comment by fructozer** [comment]
The projectiles used in projectile mechanics are entities. That means its model cannot be change in vanilla.

**Comment by iSoulEs** [comment]
> The projectiles used in projectile mechanics are entities. That means its model cannot be change in vanilla.

then how can i fix this? the first one is with armor stand mechanic, and second with Item projectile.

https://github.com/promcteam/proskillapi/assets/83812194/149f0fba-9afd-4d7b-ae7c-f376dd837ea6

**Comment by iSoulEs** [comment]
@Sentropic
