### ISSUE TITLE
Please Add Bind Skill On Specific Weapons?

### ISSUE THREAD

**Issue by Hoshino2001** [promcteam/proskillapi#6]
**Is there any way to bind skills to specific weapons?**
/class bind can only be bound to the hand-held item. 
Although Skill-GUI is the only way, I want the player to trigger skills based on combos on specific weapons.
I hope to add /class bind <skill> <itemname> because if it is the item ID, I can't make all RPG swords/custom weapons have different skills.

**Comment by goflishMC** [comment]
So, are you wanting weapons to trigger skills? like custom enchantments?

**Comment by Travja** [comment]
This was added a while ago through ProRPGItems
