### ISSUE TITLE
[Enhancement] Add cross server/bungee support

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#60]
Add cross server/bungeecord support

**Comment by BijuuKrunos** [comment]
I am a little confused, what do you mean exactly?

If you want to use skillapi on multiple Servers with the same data's. then just use the same MySQL Database, I am doing that by myself.

Or what do you want?

**Comment by goflishMC** [comment]
> 

you can do that but it doesn't sync all data properly. if you level up skills/attributes on one server and then move to another server they won't sync until that other server does /class reload or you restart the server.

**Comment by goflishMC** [comment]
> you can do that but it doesn't sync all data properly. if you level up skills/attributes on one server and then move to another server they won't sync until that other server does /class reload or you restart the server.

you can do that but it doesn't sync all data properly. if you level up skills/attributes on one server and then move to another server they won't sync until that other server does /class reload or you restart the server.

**Comment by BijuuKrunos** [comment]
than i dont know what your doing wrong. On my Network i dont have this error. Everything is synced.

**Comment by Travja** [comment]
Cross-server support appears to be working. We can re-open this if other issues present themselves.
