### ISSUE TITLE
[Bug] Issue when using particle projectile

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#61]
When using the "particle projectile" mechanic, the child components are not activating when the particle hits something.

This error is popping up in the console when I tested this: https://pastebin.com/BecDnyWx

**Comment by Tanis468** [comment]
The particle projectile issue is shared by the "Item Projectile" mechanic. It behaves identically with the same problem, so they're likely linked in some way.

**Comment by goflishMC** [comment]
This is issue was partially fixed with the latest dev version. I'm closing this ticket and opening a new one with the current issues regarding particle projectiles.
