### ISSUE TITLE
[Bug] "Item" Mechanic doesn't work for Potions

### ISSUE THREAD

**Issue by Tanis468** [promcteam/proskillapi#62]
The "Item" mechanic cannot currently spawn in specific potions as it appears to still require a numerical data value, which Minecraft no longer supports as they have switched to purely word-based data values.

From the Editor:
![image](https://user-images.githubusercontent.com/88524342/128455119-f4673d26-21dc-49ca-81c3-af9b89aadc76.png)

**Note**
This isn't an issue purely related to the Editor. 
Opening the file outside of the Editor and inputting the correct data value for modern Minecraft manually (Which is required as the Editor doesn't accept anything other than a number) doesn't appear to make it function, so there is an issue with the core mechanic itself. 

Attempting to use the old numerical data values from earlier versions of Minecraft also doesn't produce any results, just to cover that base.

**Comment by goflishMC** [comment]
I confirmed that there is no longer a way to give a potion with the id changes minecraft did in 1.13

**Comment by Travja** [comment]
This has been added in the latest dev build.
