### ISSUE TITLE
[Bug] Value Add Mechanic error if player left

### ISSUE THREAD

**Issue by springbreezex** [promcteam/proskillapi#63]
**Describe the bug**
I've created a skill with delay mechanic and a child value add mechanic. When the player left before the value-add mechanic runs, then, if the player rejoins the server, his player data cannot be loaded. (eg. /class skill attr or info will return a null pointer, and the player cannot cast any skills.)

**To Reproduce**
1. Create skill with delay (like 5 seconds) mechanic and a value add mechanic under its child
2. Leave the server before the value mechanic run
3. Wait until the mechanic ran.
4. Rejoins the server and try using any skills or commands.

**Expected behavior**

**latest.log**
No error was shown when players rejoin the server.
But null pointer exceptions will occur if the rejoint player uses any /class command.

**Versions (please complete the following information):**
1.17 Paper
SkillAPI 1.1.7

**Additional info**

**Comment by goflishMC** [comment]
can you send me this skill to test on discord @springbreezex

**Comment by springbreezex** [comment]
The error message won't produce severe issues. The above issue is due to value add mechanics. Sorry for the wrong information given. The skill is sent in discord ticket. @goflishMC
