### ISSUE TITLE
[Bug] 1.17 EntityArmorStand Bug

### ISSUE THREAD

**Issue by springbreezex** [promcteam/proskillapi#64]
**Describe the bug**
![image](https://user-images.githubusercontent.com/88456480/128636370-257e16e3-cc2b-4b55-a80d-72633b95f1fe.png)
I've set a skill with armor stand mechanic and damage mechanic targeting to an enemy. 
Normally, the armor stand will spawn and apply damage, and then despawn after some ticks. However, if the damage applied killed the entity, the armor stand will not be removed and error messages will keep looping and spaming the console. An error log is attached.
This issue has not appeared using  Paper 1.16.5. However, after updating to 1.17.1 Paper, the issue occurs.

**To Reproduce**
1. Create a skill like the above image
2. Cast the skill and kill the target using the damage mechanic
3. Error occurs

**latest.log**
https://pastebin.com/FtMBWR6h

**Versions (please complete the following information):**
-  Paper 1.17.1
 - Plugin Version: 1.1.6.1

**Comment by goflishMC** [comment]
I confirmed this is a bug. I setup a similar skill that did 3 damage to a player. The player took damage. and the armor stand disappeared.

However, after setting the damage mechanic to 50 when the player is killed with this skill the armor stand did not disappear.

Here's my armor stand still in the world after several minutes: https://i.imgur.com/5ZlsXha.png

**Comment by Travja** [comment]
This has been resolved.
