### ISSUE TITLE
[Enhancement] Remove armor stands function.

### ISSUE THREAD

**Issue by iSoulEs** [promcteam/proskillapi#640]
**Is your feature request related to a problem? Please describe.**
Working with manual animation of armor supports is difficult, even more so if you cannot remove the armor support whenever you want, but instead have to time the time when one is going to disappear to place another. This is how you make a chain and don't see a stuck animation.

**Describe the solution you'd like**
Add a function to remove armor stands (kill/remove the armor stand with the armor stand key)
like:
General -> ArmorStand Cancel
----------------------------------------------
ArmorStand Cancel
Comment "bla blah"
Icon Key: "bla bla"
Counts as Cast : on/off
Armor Stand Key: "armor stand key"
----------------------------------------------
**Describe alternatives you've considered**
Try to solve this by removing the Armor Stand with uuid. but it also makes that of other players disappear.

**Comment by iSoulEs** [comment]
also a possible future implementation is the armor stands animation.
https://git.mythiccraft.io/mythiccraft/MythicMobs/-/wikis/skills/mechanics/animatearmorstand

**Comment by Travja** [comment]
;)

**Comment by Sentropic** [comment]
You can kill entities by sending them to the void (Warp Location Mechanic to y=-500)
