### ISSUE TITLE
[Bug]: Plugin cannot handle Attributes being disabled

### ISSUE THREAD

**Issue by CrowBarJonns** [promcteam/proskillapi#645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

If the below config line is set to false, ProSkillAPI and ProRPGItems cannot load any classes, skills, or items; might need to add a handler for if GetAttributes() returns null or add a comment to the config that these plugins will break.

<img width="280" alt="image" src="https://github.com/promcteam/proskillapi/assets/69283157/2223855a-9fa5-4e7c-bb99-dc3287b2be57">

The below error will be reported in console for each class (similar error appears for item generator in ProRPGItems, will post separate bug there):
`[12:20:51] [Server thread/ERROR]: [ProSkillAPI] Failed to arrange skill tree for class "Sylvan" - Cannot invoke "com.sucy.skill.manager.AttributeManager.getKeys()" because the return value of "com.sucy.skill.SkillAPI.getAttributeManager()" is null`

### Expected Behavior

Plugin should be able to handle attributes being disabled, barring that it should not be an option in the config if it is plugin-breaking.

### Steps To Reproduce

1. Set the highlighted config line to false
![image](https://github.com/promcteam/proskillapi/assets/69283157/808b641b-f9f8-470b-b419-f18b3908679c)
2. Start the server

### Environment

```markdown
- Server Software: Purpur 1.20.2 latest
- ProSkillAPI Version: 1.2.0-R1
- ProMCCore Version: 1.1.1-R0.4
- Plugins: ProSkillAPI, ProRPGItems, ProMCCore
```

**Comment by Travja** [comment]
Ah. Yeah. That would be my fault. I did some rework with attributes a month and a half-ish ago and must have overlooked that. I'll get it fixed up shortly.
