### ISSUE TITLE
[Bug] Attribute.yml formula doesn't work as expected

### ISSUE THREAD

**Issue by springbreezex** [promcteam/proskillapi#65]
**Describe the bug**
I've tried using the attribute manager to make debuff effects. For instance, an "HPDebuff" attribute will reduce players max HP, and "MPDebuff" attribute will reduce players max MP.
```HPDebuff: 
  display: '&cHPDebuff'
  max: '999'
  icon: 'ink sack'
  icon-data: '1'
  icon-lore: 
  - '&cHPDebuff       &7[&a {amount} &7]'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    health: '-2*a+v'
```
```MPDebuff: 
  display: '&cMPDebuff'
  max: '999'
  icon: 'ink sack'
  icon-data: '1'
  icon-lore: 
  - '&cMPDebuff       &7[&a {amount} &7]'
  global: 
    condition:  {}
    mechanic:  {}
    target:  {}
  stats: 
    mana: '(-1)*a+v'
```
However, no changes have been made even players have several amounts of this attribute. None of the formulas (`'-a+v' '-1*a+v' 'v-a'`) are working as well.

Paper 1.16.5 / 1.17.1
Plugin version 1.1.6.1

**Comment by Travja** [comment]
This has been addressed. To the best of my knowledge, this works as intended now.
