### ISSUE TITLE
[Bug] Particle Projectile issue with damage mechanic

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#66]
When adding damage to particle projectile mechanic the damage value is only 1 no matter how much damage is set in the damage mechanic.

This is my test skill in action: https://i.imgur.com/bcIpZ0g.png

This is how much the damage mechanic was set to: https://i.imgur.com/nA1QIBF.png

This is how the skill was setup: https://i.imgur.com/Yh30rgr.png

**Comment by Travja** [comment]
Current status. Seems to be resolved more-or-less. This specifically is an issue where, in part, ProRPGItems and ProSkillAPI interfere a little bit. This has been address. It also seems to be largely tied to the formatting of the custom damage sections in ProPRGItems. Should this issue arise again, these would be the things to check.

goflish is experiencing additional damage above the set value regardless of ProRPGItems being installed or not.

**Comment by Travja** [comment]
The extra damage appears to be from the `intelligence-base` attribute on the selected class.
