### ISSUE TITLE
[Bug] Immunity multiplier broken

### ISSUE THREAD

**Issue by RebelRanger** [promcteam/proskillapi#67]
The immunity mechanic is providing full immunity regardless of the multiplier. 

**To Reproduce**
Simplest way to reproduce this is to make a skill that launches the player into the air and grants 50% fall damage immunity. Cast the skill and you will notice that it will completely negate the fall damage.  Seemed to be working on 1.1.6 Skilapi. 

**Versions (please complete the following information):**
-  Spigot Version: 1.17.1-189
 - Server Version: 1.17.1
 - Plugin Version: ProSkilApi-1.1.7_01-DEV

**Comment by goflishMC** [comment]
We tested with this skill and it works fine. Closing this issue, feel free to reopen if you need more help.

[immunityskill.zip](https://github.com/promcteam/proskillapi/files/7034249/immunityskill.zip)
