### ISSUE TITLE
[Bug] [Forcecast and repeat mechanic]

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#69]
**Describe the bug**
user has reported the forcecast command will not trigger repeat mechanic if the skill hasn't been invested skill points.

If the skill is trigger by console forcecast command with points invested, the debug messages are shown as below. The line debug is sent under repeat mechanic

https://i.imgur.com/U5o83Rf.png

If the skill is trigger by console forcecast command with NO points invested, the debug messages are shown as below. The line debug is NOT send (because it is under repeat mechanic). But the other mechanics are running.

https://i.imgur.com/04Il5aL.png

**Comment by Travja** [comment]
I've addressed this in the most recent dev build. No promises that it didn't also create other issues. I haven't tested thoroughly.
