### ISSUE TITLE
The cancel machanic is not working at all.

### ISSUE THREAD

**Issue by ArcaneFlame520** [promcteam/proskillapi#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Steps To Reproduce

It just happend

### Environment

```markdown
- Server Software: Spigot
- ProSkillAPI Version:latest
- ProMCCore Version:latest
- Plugins:just proskillapi and promccore
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# paste log here...
```

</p>
</details>

**Comment by Travja** [comment]
"Latest" is not helpful. I can't help you if I don't know what versions of the plugins you're using

**Comment by ArcaneFlame520** [comment]
ok

**Comment by ArcaneFlame520** [comment]
proskillapi-1.3.0-R0.20-20240227.052819-1 and promccore-1.2.0-R2

**Comment by ArcaneFlame520** [comment]
hello this is kinda needed I keep fireing 2 arrows when i say cancel and i take damage when i say cancel please help

**Comment by Travja** [comment]
Grab the actual latest off of Spigot or Discord.

**Comment by ArcaneFlame520** [comment]
ok

**Comment by ArcaneFlame520** [comment]
there is only a new version of proskillapi so ill try that

**Comment by ArcaneFlame520** [comment]
now there are not any particles on my arrow

**Comment by ArcaneFlame520** [comment]
Help me please
The arrow is cancled the sounds play and an arrow fires. But when i take the cancel event away the arrow fires and particles show

**Comment by Travja** [comment]
Share your skill

**Comment by ArcaneFlame520** [comment]
'Fire Arrow': 
  name: 'Fire Arrow'
  type: 'Arrow'
  'max-level': 1
  'skill-req-lvl': 0
  'needs-permission': 'false'
  'cooldown-message': 'true'
  attributes: 
    'level-base': '1'
    'level-scale': '0'
    'cost-base': '1'
    'cost-scale': '0'
    'cooldown-base': '40'
    'cooldown-scale': '0'
    'mana-base': '15'
    'mana-scale': '0'
    'points-spent-req-base': '0'
    'points-spent-req-scale': '0'
    incompatible: []
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'BLAZE_POWDER'
  'icon-data': 0
  'icon-durability': 0
  'icon-lore': 
  - '&d{name} &7({level}/{max})'
  - '&2Type: &6{type}'
  - ''
  - '{req:level}Level: {attr:level}'
  - '{req:cost}Cost: {attr:cost}'
  - ''
  - 'Fire a fire arrow.'
  - ''
  - '&2Mana: {attr:mana}'
  - '&2Cooldown: {attr:cooldown}'
  desc: []
  components: 
    Launch: 
      type: 'trigger'
      data: 
        mana: 'false'
        cooldown: 'false'
        type: 'Arrow'
      preview: 
        enabled: 'false'
      children: 
        Value: 
          type: 'condition'
          data: 
            'icon-key': ''
            key: 'ArrowFire?'
            'min-value-base': '1'
            'min-value-scale': '0'
            'max-value-base': '1'
            'max-value-scale': '0'
          preview: 
            enabled: 'false'
          children: 
            'Value Set': 
              type: 'mechanic'
              data: 
                'icon-key': ''
                counts: 'false'
                key: 'ArrowFire?'
                'value-base': '0'
                'value-scale': '0'
                save: 'false'
              preview: 
                enabled: 'false'
              children: {}
            Projectile: 
              type: 'mechanic'
              data: 
                'icon-key': ''
                counts: 'false'
                projectile: 'Arrow'
                flaming: 'false'
                cost: 'One'
                'override-item': 'true'
                homing: 'false'
                'velocity-base': '3'
                'velocity-scale': '0'
                'lifespan-base': '20'
                'lifespan-scale': '0'
                'on-expire': 'false'
                spread: 'Cone'
                'amount-base': '1'
                'amount-scale': '0'
                'angle-base': '30'
                'angle-scale': '0'
                'forward-base': '0'
                'forward-scale': '0'
                'upward-base': '0.5'
                'upward-scale': '0'
                'right-base': '0'
                'right-scale': '0'
                particle: 'Dust color transition'
                'dust-color': '#FF0000'
                'final-dust-color': '#ffdd00'
                'dust-size': '1'
                arrangement: 'Sphere'
                'radius-base': '0.4'
                'radius-scale': '0'
                'particles-base': '20'
                'particles-scale': '0'
                'visible-radius': '76'
                dx: '0'
                dy: '0'
                dz: '0'
                amount: '1'
                speed: '0'
                'use-effect': 'false'
              preview: 
                enabled: 'false'
                period: '5'
                'per-target': 'false'
                path: 'false'
              children: 
                Fire: 
                  type: 'mechanic'
                  data: 
                    'icon-key': ''
                    counts: 'false'
                    'damage-base': '4'
                    'damage-scale': '0'
                    'seconds-base': '6'
                    'seconds-scale': '0'
                  preview: 
                    enabled: 'false'
                  children: {}
            Sound: 
              type: 'mechanic'
              data: 
                'icon-key': ''
                counts: 'false'
                sound: 'Entity arrow shoot'
                'volume-base': '100'
                'volume-scale': '0'
                'pitch-base': '1'
                'pitch-scale': '0'
              preview: 
                enabled: 'false'
              children: {}
            'Sound-b': 
              type: 'mechanic'
              data: 
                'icon-key': ''
                counts: 'false'
                sound: 'Block campfire crackle'
                'volume-base': '100'
                'volume-scale': '0'
                'pitch-base': '1'
                'pitch-scale': '0'
              preview: 
                enabled: 'false'
              children: {}
    'Cast-0': 
      type: 'trigger'
      data: {}
      preview: 
        enabled: 'false'
      children: 
        'Value Set': 
          type: 'mechanic'
          data: 
            'icon-key': ''
            counts: 'true'
            key: 'ArrowFire?'
            'value-base': '1'
            'value-scale': '0'
            save: 'false'
          preview: 
            enabled: 'false'
          children: {}
        Sound: 
          type: 'mechanic'
          data: 
            'icon-key': ''
            counts: 'false'
            sound: 'Entity arrow hit player'
            'volume-base': '100'
            'volume-scale': '0'
            'pitch-base': '1'
            'pitch-scale': '0'
          preview: 
            enabled: 'false'
          children: {}


Like this?

**Comment by ArcaneFlame520** [comment]
Like This?
Fire Arrow:
  name: Fire Arrow
  type: Arrow
  max-level: "1"
  skill-req-lvl: 0
  needs-permission: false
  cooldown-message: true
  msg: "&6{player} &2has cast &6{skill}"
  combo: ""
  icon: Blaze powder
  icon-data: 0
  icon-lore:
    - "&d{name} &7({level}/{max})"
    - "&2Type: &6{type}"
    - ""
    - "{req:level}Level: {attr:level}"
    - "{req:cost}Cost: {attr:cost}"
    - ""
    - Fire a fire arrow.
    - ""
    - "&2Mana: {attr:mana}"
    - "&2Cooldown: {attr:cooldown}"
  attributes:
    level-base: 1
    level-scale: 0
    cost-base: 1
    cost-scale: 0
    cooldown-base: "40"
    cooldown-scale: 0
    mana-base: "15"
    mana-scale: 0
    points-spent-req-base: 0
    points-spent-req-scale: 0
    incompatible: []
  components:
    Cast:
      type: trigger
      comment: ""
      children:
        Value Set:
          type: mechanic
          comment: ""
          data:
            icon-key: ""
            counts: true
            key: ArrowFire?
            value-base: 1
            value-scale: 0
            save: false
        Sound:
          type: mechanic
          comment: ""
          data:
            icon-key: ""
            counts: false
            sound: Entity arrow hit player
            volume-base: 100
            volume-scale: 0
            pitch-base: 1
            pitch-scale: 0
    Launch:
      type: trigger
      comment: ""
      data:
        mana: false
        cooldown: false
        type: Arrow
      children:
        Value:
          type: condition
          comment: ""
          data:
            icon-key: ""
            key: ArrowFire?
            min-value-base: 1
            min-value-scale: 0
            max-value-base: "1"
            max-value-scale: 0
          children:
            Value Set:
              type: mechanic
              comment: ""
              data:
                icon-key: ""
                counts: false
                key: ArrowFire?
                value-base: "0"
                value-scale: 0
                save: false
            Projectile:
              type: mechanic
              comment: ""
              preview:
                enabled: false
                period: 5
                per-target: false
                path: false
              data:
                icon-key: ""
                counts: false
                projectile: Arrow
                flaming: false
                cost: One
                override-item: true
                homing: false
                velocity-base: "3"
                velocity-scale: 0
                lifespan-base: "20"
                lifespan-scale: 0
                on-expire: false
                spread: Cone
                amount-base: 1
                amount-scale: 0
                angle-base: 30
                angle-scale: 0
                forward-base: 0
                forward-scale: 0
                upward-base: "0.5"
                upward-scale: 0
                right-base: 0
                right-scale: 0
                particle: Dust color transition
                dust-color: "#FF0000"
                final-dust-color: "#ffdd00"
                dust-size: 1
                arrangement: Sphere
                radius-base: "0.4"
                radius-scale: 0
                particles-base: 20
                particles-scale: 0
                visible-radius: "76"
                dx: 0
                dy: 0
                dz: 0
                amount: 1
                speed: "0"
                use-effect: false
              children:
                Fire:
                  type: mechanic
                  comment: ""
                  data:
                    icon-key: ""
                    counts: false
                    damage-base: "4"
                    damage-scale: 0
                    seconds-base: "6"
                    seconds-scale: "0"
            Sound:
              type: mechanic
              comment: ""
              data:
                icon-key: ""
                counts: false
                sound: Entity arrow shoot
                volume-base: 100
                volume-scale: 0
                pitch-base: 1
                pitch-scale: 0
            Sound-b:
              type: mechanic
              comment: ""
              data:
                icon-key: ""
                counts: false
                sound: Block campfire crackle
                volume-base: 100
                volume-scale: 0
                pitch-base: 1
                pitch-scale: 0

**Comment by Travja** [comment]
Either the file or hitting "Share Skill" on the editor and sending the link would work better

**Comment by ArcaneFlame520** [comment]
https://paste.travja.dev/pasakefiga

**Comment by ArcaneFlame520** [comment]
Well can you help?

**Comment by Travja** [comment]
Since you're cancelling the arrow and replacing it with a new arrow, the placement of the cancel mechanic matters. Since if you do it before, you're actually going to be cancelling the projectile launch mechanic. So just put the cancel mechanic _after_ the projectile mechanic.

**Comment by ArcaneFlame520** [comment]
ill try

**Comment by ArcaneFlame520** [comment]
OK that worked thanks alot.
