### ISSUE TITLE
[Bug] Kicked from server when punching player

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#7]
**Describe the bug**
I punched a player and got kicked from the server with this message: https://i.imgur.com/oA6eEtq.png

**To Reproduce**
Maybe punch a player?

**Expected behavior**
Player should have taken damage and I should not have been kicked.

**Versions (please complete the following information):**
-  Spigot Version: 1.16.5
 - Plugin Version: 1.98

**Comment by dinobossytnew** [comment]
yes bug

**Comment by goflishMC** [comment]
This seems like a random issue that only happened once and has never happened again, also no other user has reported this issue, so I'm closing this.
