### ISSUE TITLE
[Bug] Problem with click combos when you using F

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#82]
**Describe the bug**
When you use F in a click combo you are unable to use /class skill, it causes an error: https://pastebin.com/Nb6zSMT2

**To Reproduce**
Example steps (replace with your steps)
Enable click combos and when setting up your skill use an F in the combo

**Expected behavior**
You should be able to use /class skill to add/remove points and to view your skills, but you can't

**Comment by goflishMC** [comment]
fixed in latest dev build

**Comment by k437u** [comment]
doesn't work on mc version 1.17.1
tried the mentioned dev build and it didn't work out as well
