### ISSUE TITLE
[Bug]: Casting with item (/class bind) causes cooldown to be displayed 2x

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you bind a skill to an item and right click while looking at a block it will trigger the cooldown to show up twice in chat.

### Expected Behavior

The cooldown that shows up in chat should only show once per cast.

### Steps To Reproduce

1. Bind a skill to your item
2. Look at a block when you cast it

### Environment

```markdown
- Server Software: 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://i.imgur.com/byCrYmR.jpeg
```

### latest.log

there are no errors

**Comment by Travja** [comment]
I'm not getting this behavior. Might have been fixed by recent updates, so I'll mark this as resolved.
