### ISSUE TITLE
[Bug] Commands with player names not working

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#9]
Commands that require a players name do not work.

like /class exp Dimrok 1 class does not work, but I do /class exp 1, it will give me 1 exp.

See this image: https://i.imgur.com/U1N7dYC.png

For some reason the command breaks when you try to use the players name in the command

**Comment by BijuuKrunos** [comment]
same for me, this has something to do with the server software as well. I am on paper-465 here is everything fine but after that (this is not exaclty, next version i tested was 500) this error is comming. please fix, I want to update my paper Version xD thx for taking over this project ^^

**Comment by goflishMC** [comment]
> same for me, this has something to do with the server software as well. I am on paper-465 here is everything fine but after that (this is not exaclty, next version i tested was 500) this error is comming. please fix, I want to update my paper Version xD thx for taking over this project ^^

we're going to fix it, thanks for the report.

**Comment by goflishMC** [comment]
Fixed in dev build Alpha 1.1
