### ISSUE TITLE
[Bug]: /class bar command doesn't do anything

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using /class bar seems to be broken, nothing happens when using the command.

### Expected Behavior

Should open something, not sure what it's supposed to open. The wiki says, "Toggles skill bar on/off (if enabled in the config)"

### Steps To Reproduce

Type /class bar

### Environment

```markdown
- Server Software: 1.17.1
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://i.imgur.com/byCrYmR.jpeg
```

**Comment by Travja** [comment]
I actually haven't been having issues with this. I've been using it in my testing the last couple of days. It merely toggles the skill bar on/off.

**Comment by Travja** [comment]
I'll just add here that `Skill bar.enabled` has to be set for true for this to work.
